README.md, lib/match_body.js, tests/test_intercept.js
I really need this feature that allows you to give a request spec as a RegExp (actually, only by string)
So you can write cool stuff like:
```javascript
var scope = nock('http://www.google.com')
.post('/echo', 'key=v.?l')
.reply(200, function(uri, body) {
return 'OK !';
});
```
And be able to match requests like `POST http://www.google.com/path key=val`or `key=vul`, or even `key=vl`if you want. 
If the provided pattern is actually not a valid RegExp, then nock considers it as a basic string.
=> added RegExp comparison so you can provide RegExp in post request spec

lib/recorder.js, package.json, tests/test_recorder.js
We use the restler library, and it returns the chunks of data as strings.  Because of that the record feature was throwing an error.  I don't see a reason why nock can't just convert each chunk to a buffer object, then process.  
I have added a test that breaks without the change to lib/recorder.js
=> Nock shouldn't crash if encoded data is in string form

README.md, lib/scope.js, tests/test_intercept.js
This adds the ability to automatically inject the `Date` and `Content-Length` headers. They are hidden behind new methods, so it does not conflict with current behavior:
This adds the `Date` header to the reply, formatted via `Date#toUTCString()`
```js
scope.replyDate(); // creates an implicit new Date()
scope.replyDate(new Date(2015, 0, 1)); // uses 01-01-2015 as the date
```
This is just a flag method (like `scope.persist()`) that allows automatically filling in the `Content-Length` header when `scope.reply(...)` is used to inject JSON data.
```js
scope.replyContentLength()
```
If you think this is worth merging, I can update the documentation to reflect these new methods before it is merged.
=> Adding "Date" and "Content-Length" headers (hidden behind new methods)

lib/intercept.js, tests/test_https_allowunmocked.js
When nocking a https server with allowUnmocked enabled, fetching unmocked path could not get any data. 
Please refer to the test case for details.
=> Fix https+allowunmocked

README.md, lib/recorder.js, tests/test_recorder.js
Hey Pedro @pgte , I'm Peter :)
I'm trying to do a few things with nock.
* Write nock output to a custom log file
* Using objects
* Without the separators
So I needed to add some code for that!
I added a test and documentation for logging.  (The gitter.im chat had that question come up.)  I also added the `use_separator` option, which defaults to true, but allows you to suppress it.  I remember using nock a year ago and I thought the "cut here" string was distracting.
Let me know what you think!
=> Suppress seperator and tests

README.md, lib/request_overrider.js, lib/scope.js, lib/socket.js, tests/test_intercept.js
By passing in a socket timeout to the nock request, it will emit a timeout event on the request if setTimeout has been called with a lower value. It does not actually wait for the specified period of time.
I've checked that this works with the base http library's request.setTimeout and socket.setTimeout, both with a "once" function and an "on timeout" handler.
I wanted to first check if this approach makes sense, and if so I can flesh it out with tests and documentation.
This is related to #164, though for one specific case.
=> simulate socket timeout

lib/recorder.js, lib/request_overrider.js, tests/test_intercept.js
I am trying to do the following:
```
function readAws() {
return nock('https://s3.amazonaws.com')
.filteringPath(function filter(_path) {
id = _path.replace('/' + bucket + '/', '');
return _path.replace(id, 'XXX');
})
.get(u)
.reply(200, function() {
console.log(arguments);
var s = through();
s.setEncoding = function() {};
console.log("ID", id);
local.read(id, function(err, data) {
if (err) throw err;
s.queue(encode(data));
s.end();
});
return s;
});
}
```
The aim is to basically use the local file storage api to mock the remote aws one.
But by the time I am reading the buffer, it is still empty.
The good call would be to be able to get a callback on the reply callback function in order to tell nock when it is finished.
=> reply with an asynchroneous response.

lib/intercept.js, tests/test_back.js, tests/test_intercept.js, tests/test_net_connect.js
Just showing the hostname in the error is not descriptive enough. It's more useful to show the full path, so that the developer can easily determine which request is causing the error.
=> Show path in NetConnectNotAllowedError

.coveralls.yml, .gitignore, .istanbul.yml, README.md, package.json, tests/test.js, tests/test_net_connect.js, tests/test_redirects.js
#237 
I used [istanbul](https://github.com/gotwarlost/istanbul) for coverage.
All tests are run from one file. Because nock functions as a singleton I had to reorder the tests until it worked.
I replaced the test pre-commit with the coverage since it runs all the tests too. It's set to reject commits if coverage is not at least 90% globally. Run `istanbul help config` to see what other options are available.
I integrated with [coveralls.io](https://coveralls.io/) to get the coverage badge. You can see the current coverage from my repo. If you decided to keep coveralls you would just have to setup your own account, add your repo in coveralls, replace the repo token in `.coveralls.yml`, and update the badge url.
=> Code Coverage

lib/scope.js
Hello everyone,
on our project with experienced the same problem as described in #235.
As the author concludes nock doesn't return data because the fs readstream is already read to the end and cannot be read a second time.
My proposed fix is to create a new fs read stream if the counter set by .times() (or an alias) has not yet reached zero. This fixes the freeze in our test cases.
Best regards,
Benjamin
=> Fix #235: Reset file read stream after first request

README.md, lib/scope.js, tests/test.js, tests/test_basic_auth.js
This PR adds some syntax sugar for basic authentication:
```js
nock('http://super-secure.com')
.get('/test')
.basicAuth({ user: 'foo', pass: 'bar' })
.reply(200, 'Here is the content');
```
=> add syntax sugar for basic auth

lib/recorder.js, lib/request_overrider.js, package.json, tests/test_back_2.js, tests/test_intercept.js, tests/test_recorder.js
The [Node API](https://nodejs.org/api/http.html#http_http_incomingmessage) specifies that HTTP responses should be instances of `http.IncomingMessage`. Not following the API specification breaks libraries that depend on this API contract. These changes update Nock's behavior to be compliant with the Node API.
It's worth pointing out that I modified the behavior of a few existing test cases in this change. My understanding is that these changes more accurately reflect Node's actual behavior, but I'm open to feedback if I it seems that I missed something or if I misunderstood the intent of any of the tests.
=> Use http.IncomingMessage for response objects.

lib/back.js, lib/intercept.js, tests/test_back.js
Net connection is incorrectly disabled when adding nock to a project that already has unit tests but no nocks (recorded or manual). So this:
```
var nockBack = require('nock').back;
nockBack.fixtures = './fixtures/nock';
```
immediately breaks already existing tests.
=> Fix nockBack dryrun mode allows no net access by default

README.md, lib/mixin.js, lib/request_overrider.js, tests/test_intercept.js
This change provides the ability to generate header values and
default header values by evaluating a function. The function is
passed the request, response, and body (if available). The return
value is used as the header value.
Closes #263.
=> Use functions to generate header values.

package.json
The version spec continus to allow chai ^1.9.2
=> Allow use with chai 2.x

lib/match_body.js, package.json, tests/test_common.js
Nock currently uses the `deepEqual` function from node's assert module to match request bodies. This checks nested attributes using coercive `==` equality, which means that `{"number": "1"}` matches `{"number": 1}`.
This issue left me with a broken test that went unnoticed for a while. This pull request modifies the `matchBody` function to use [substack's deep-equal module](https://github.com/substack/node-deep-equal) with strict mode on, instead of node's assert. This ensures that all deep comparisons happen using strict `===` equality.
=> Use strict equality for deep comparisons

lib/match_body.js
If no content type provided with function to match request parameters it will fail with specified error
Try this:
```
let nockRequest = nock('https:/...')
.replyContentLength()
.post('/httppost', function(body){
return true;
}).reply(401, "");
```
=> Fix for Uncaught TypeError: Cannot read property 'match' of undefined

lib/scope.js, tests/test_intercept.js
My proposal for supporting query string matching, following the feel of the `query()` function of superagent. Should help for #82 and #274
Using the new `query()` function you can match query strings in any order (also accepts regexp query string values)
```js
// will match 'http://google.com/?foo=bar&baz=foz' or 'http://google.com/?baz=foz&foo=bar'
nock('http://google.com')
.get('/')
.query({foo:'bar', baz:'foz'})
.reply(200);
```
=> Add support for query string matching

README.md
- Use high-res svg badge for Buld Status.
- Use `flat` instead of `flat-square` badge style for consistency with other all other badges.
=> readme: svg badge for build status, flat style

lib/scope.js, tests/test_intercept.js
Hi!
This PR adds a little feature that will make the life of test-writers a tiny bit easier. The `query()` method now calls `toString()` for Number and Boolean values that were passed to it, and converts `undefined` and `null` to empty strings `''`. That way `query()` mimics the behavior of `querystring.stringify()`.
I think it will save some unknown, new to nock developer his precious time, when he is trying to figure out why does the query string in the request and in the nock server don't match, when visually they do.
PS I had to fix a test that didn't pass on my machine.
=> query() accepts various typed values

lib/scope.js, tests/test_intercept.js
`query()` arguments are now properly encoded.
I had to fix the test too as it wasn't actually testing the encoding.
=> query() encoding fix

package.json
Latest version of chai 3.x is 3.2.0. The current semver string in package.json does not allow/match 3.2.0. 
Current:
```
"chai": ">=1.9.2 <3.0.0",
```
Recommened:
```
"chai": ">=1.9.2 <4.0.0",
```
=> update chai semver to support versions < 4.0.0 (FIX #361)

README.md
The body from this is empty because there is no status code:
```
nock('http://example.com')
.get('/users')
.query({name: 'pedro', surname: 'teixeira'})
.reply({results: [{id: 'pgte'}]});
```
```js
nock('http://example.com')
.get('/users')
.query({name: 'pedro', surname: 'teixeira'})
.reply(200, {results: [{id: 'pgte'}]});
```
=> doc fix - several .reply calls are made without a status, so there is no body.

.travis.yml, lib/request_overrider.js, lib/scope.js, lib/socket.js, package.json, tests/test_basic_auth.js, tests/test_data.js, tests/test_dynamic_mock.js, tests/test_intercept.js
When using just an username for authentication, the password `undefined` would be used instead of `''`.
Depends on #369 (a rebase is required).
=> Fix authentication using username only

lib/scope.js, tests/test_intercept.js
This is a fix for a small bug I found in the `query()` handler.
Currently the `query()` option (if passed an `Object`) loops through all passed values and compares them against a set of expected values. This will throw a false positive if the user passes fewer values than expected but all of them match the expected params.
For example, if setup as follows:
```javascript
var scope = nock('http://google.com')
.get('/')
.query({
num:1,
str:'fou'
})
.reply(200);
```
The following requests will all match:
```
http://google.com?num=1
http://google.com?str=fou
http://google.com?str=fou&num=1
```
By checking that there is an equal number of expected and passed params we can at preempt any unnecessary comparison and catch some false positives.
=> Fix query() unpassed param issue

README.md, lib/scope.js, package.json, tests/test_intercept.js
This PR adds the ability to specify request headers which should either match a Regular Expression or satisfy a function. It also adds positive & negative tests around the functionality.
=> Specify Regex or Function to check Request Headers

README.md, lib/back.js, tests/test_back.js
An `afterRecord` option can be passed in which will be called with the array of scopes as a parameter. The function can then filter these as it wishes and return the array of scopes that will be saved to the
fixture.
This fixes #300.
This is my first time in this codebase so please suggest anything :+1:
=> Allow filtering nock back recording before saving

README.md, lib/intercept.js, lib/scope.js, tests/test_intercept.js
This PR exposes the `isDone()` function to the global scope. It allows users to determine if all expectations have been met.
Note that I also corrected the _README_ which previously implied that this behaviour was already possible.
=> Add `isDone()` to global scope

tests/test_intercept.js
The previous PR lowered the code coverage a bit because the `isDone()` function wasn't being tested when an expectation was not yet met.
Refs #388
=> Improve code coverage for `isDone` method

README.md, lib/intercept.js, lib/scope.js, tests/test_intercept.js
This PR is similar to #388 and exposes the pendingMocks() function to the global scope. It allows users to determine which expectations have not been met.
=> Add `pendingMocks()` to global scope

README.md
I'm just getting picky here but I didn't put together the `enableNetConnect` and localhost when I was testing my express server, after "CTRL+F" ing my way through the README I came across: https://github.com/pgte/nock/issues/239 
Thanks
=> Added localhost enableNetConnect to README

lib/recorder.js, lib/scope.js, tests/test_intercept.js, tests/test_recorder.js
When enabled, prevents calling of `encodeURIComponent` on query param keys and values.
Additionally, this option is automatically set for scopes generated by the record feature, which is correct because query params are already encoded by the time they are added to these scopes.
=> New option 'encodedQueryParams'; fixes #413.

lib/common.js
Ran across this issue when trying to specify content-length header on a .reply().  The call to headersFieldNamesToLowerCase() always returns {} for headers.
Sorry for the lack of tests, it's after 6pm and trying to finish up a production issue.
=> The underscore wrapped version reads better, only it doesn't work.

lib/match_body.js, tests/test_common.js
Ok, this one took me a while.
`matchBody` [strips line endings](https://github.com/pgte/nock/blob/master/lib/match_body.js#L18) to be consistent across OSs. While this is cool in 99.99% of the cases, it fails when it comes to multipart requests, since mulitpart parsers depend on the line breaks.
This PR disables stripping when `Content-Type` header contains "multipart".
Additionaly a bug is fixed, where matchBody was throwing, when headers came as array (node-fetch style #399, #400).
=> Fix matchBody for multipart requests

lib/request_overrider.js
Commit 48e8be5 added a compatibility fix for users of the request
NPM module and strict SSL cert checking. The request module has
since been updated (see https://github.com/request/request/pull/1615
for more details), and a corresponding change should be made in
nock to ensure compatibility.
=> Update #158 fix for request module and strict SSL

README.md, lib/common.js, lib/intercept.js, lib/request_overrider.js, lib/scope.js, tests/test_common.js, tests/test_intercept.js
Related to https://github.com/pgte/nock/issues/347, but I did first for `domain`. 
If you like this line, I can implement for the `path` as well (Now that I break the matches by `URL part` will be much easier to add `regex match` at `paths`).
Just let me know and I can implement in this pull request or in a new one after the merge.
**Notes:**
- I removed the `hasHadInterceptors` because it has almost the same responsibility of `interceptorsFor`, so I've adapted to have a single method to return the proper interceptor;
- I tried to avoid changing the `allInterceptors` structure, but couldn't find any easy way to store the regex as the key of the object;
**Example:**
```js
var scope = nock(/regexexample\.com/)
.get('/resources')
.reply(200, 'Match regex'); …
```
=> add ability to match domain using regex

lib/scope.js, tests/browserify-public/browserify-bundle.js, tests/test_intercept.js
solve issue https://github.com/pgte/nock/issues/347 by adding interceptor callback to match uri. Like that:
```javascript
var validUrl = [
'/cats',
'/dogs'
];
nock('http://www.example.com')
.get(function(uri) {
return validUrl.indexOf(uri) >= 0;
})
.reply(200, 'Match callback');
```
=> [feature] match uri using callback

lib/common.js, package.json, tests/browserify-public/browserify-bundle.js
This PR tries to fix #423. Here thanks @jdalton 's suggestion, the reason of test code failed is the execution of chain becomes lazy so we have to call `value()` to fire it. see: https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings
=> Upgrade to lodash 3.0, fix #423

lib/request_overrider.js, tests/test_intercept.js
Fixes #454 
1. Reply header functions were evaluated twice per request.
2. Reply header functions were overridden by evaluated values.
After fix each header function is evaluated only once per request.
After fix each header function is evaluated on each and every request separately.
=> Fixed issue with header function evaluation + added 2 tests

lib/match_body.js
recorded bodies can be an object (json).  dont try to use a string function on them.
=> dont execute `replace` on a non-string

lib/intercept.js, lib/interceptor.js, lib/request_overrider.js, tests/test_intercept.js
When a large number of requests are nocked and the interceptor list is large, the amount of time spent processing request is larger than it needs to be. I've pushed a couple of fixes that optimize nock for the scenario with a large number of interceptors.  
If there are any issues I'm happy to address them. I've run with these changes in my own project testing and it works faster for me.
=> Optimize for large number of interceptors

README.md, lib/intercept.js, tests/test_intercept.js
Previously `nock.removeInterceptor()` only took an options object. This was inconvenient if the client didn't wish to expose urls directly in their tests.
`removeInterceptor()` now takes both the original options object, or an alternative instance of `Interceptor` and uses the instance variables `baseUrl` and `_key` to filter for removal.
Added 3 test cases to cover http, https and regex path matching.
I'm not 100% sure this PR covers all cases of `Interceptor` object's `baseUrl` variable being consistent with the keys of `allInterceptors`, was hoping you could clarify that.
**Resolves #447**
=> Call `nock.removeInterceptor()` with interceptor instance

lib/scope.js
You cannot effectively compare anything to an empty object declaration. {} === {} will always equal false. This is to address the attended purpose by the comment provided. 
Found this while I was on my hunt down for why nock.define() fails when reqheader['content-type'] is provided on post routes.
=> Use lodash size function

lib/recorder.js, tests/test_recorder.js
Fixes #486 
After investigation, the issue is that the `recorder` assumes that all listeners are attached after http.request's `callback` is called which might not be the case. That's exactly what was happening with me because since [got](https://github.com/sindresorhus/got) is using promises, the `data` event was only attached in the next event loop.
Test case & fix added, I haven't committed the browserify bundle. I've tried to follow the coding style, let me know if something needs to be changed.
=> Do not automatically consume responses, respect original consumer.

README.md
I've been trying to use `nock` with `got` and it eats errors from the `ClientRequest` object. Debugging how this worked took long enough that I think it's worth a note.
=> Make the source of NetConnectNotAllowedError clear

lib/intercept.js, tests/test_events.js
Previously if you disabled net connect via `nock.disableNetConnect`,
`nock.emitter.on('no match')` would return undefined for its first argument,
since `req` is never initialized. Replaces `req` with `options`, which is
present and set to a Url instance.
Fixes the global nock.emitter.on event listener to remove all event listeners
at the end of each test, otherwise an event listener registered in one test
might bleed over into the next.
(This might not be the right fix, I'm happy to change as necessary).
=> Fix nock.emitter.on('no match') undefined argument

lib/intercept.js, lib/request_overrider.js, tests/test_intercept.js
From the issue reported on https://github.com/node-nock/nock/issues/508. 
The regex domain interceptor wasn't being removed from the list because the method was using `protocol + host` to find the interceptor in the list. Changed to use `interceptor.basePath` which is reliable for any kind of interceptor.
=> properly remove interceptor with regex domain from the list after used

README.md
Fixes #702 
> The TravisCI badge on the project page shows "Build passing," but the tests are in fact failing – https://travis-ci.org/node-nock/nock. (The src on the badge seems to be incorrect.)
>
> The test that is failing is also failing locally.
=> Use public TravisCI badge icon, which shows failing tests

lib/common.js, lib/interceptor.js, lib/recorder.js, lib/request_overrider.js, lib/scope.js, tests/browserify-public/browserify-bundle.js, tests/test_intercept.js
=> Leave rawHeaders case untouched on nock's replies

lib/match_body.js, tests/test_body_match.js
Closes #715 and does not appear to cause any regressions.
=> Handle arrays like objects in match_body

lib/intercept.js, tests/browserify-public/browserify-bundle.js, tests/test_intercept.js
Currently when you call `nock.removeInterceptor(interceptor)` it stops that interceptor from doing any more intercepting, but doesn't remove it from `pendingMocks()` (this is part of https://github.com/node-nock/nock/issues/600).
This fixes that, by updating the interceptor's scope to remove it properly. I.e. with this change, pendingMocks is now empty at the end, as expected:
```javascript
var interceptor = nock('http://example.org').get('/somepath');
var scope = interceptor.reply(200, 'hey');
nock.removeInterceptor(interceptor);
scope.pendingMocks() // Empty;
```
It looks like there's a separate issue in #600 that I haven't looked at about how `nock.pendingMocks()` behaves with scope reuse. This patch doesn't fix that (and I'm probably not going to, since it doesn't affect me).
This …
=> Update PendingMocks when an interceptor is removed

README.md, lib/intercept.js, lib/interceptor.js, lib/scope.js, tests/browserify-public/browserify-bundle.js, tests/test_intercept.js
This PR adds `optionally()`, so you can define mocks that might happen, but not worry about it if they don't (I'm using this for some common test setup where for almost every test in need a basic request mocked out, but not for all of them).
Along the way I noticed `isDone()` and `pendingMocks()` weren't actually consistent. Only `isDone()` ever considered persisted mocks to be 'done' (they stayed in `pendingMocks()` forever), and only `isDone()` supported `options.requireDone` (see below). I've now made them consistent so, tidied the implementations together, and simplified this significantly on the way.
There was an existing feature sort-of like `optionally()` already present: you could pass `requireDone: false` as an option to an interceptor. Passing as an option is less nice UX for my …
=> Add optionally() and make isDone and pendingMocks consistent.

lib/match_body.js, tests/test_body_match.js
This adds a test for empty objects in the body and spec.
It also fixes a regression that would cause the library to throw an error if an empty object was passed in the body.
CC @vrinek
=> Fixes regression introduced by #719

lib/common.js, lib/request_overrider.js, tests/test_gzip_request.js
This pull request adds corresponding decoders when content encoding is 'gzip'`or`'deflate'`, but only if the content type is JSON. 
Motivation:
currently, nock tries to parse JSON from the requestBody even if it is compressed and ultimately fails with a `SyntaxError`:
```
SyntaxError: Unexpected token f in JSON at position 1
at Object.parse (native)
at RequestOverrider.end (/omitted/node_modules/nock/lib/request_overrider.js:298:28)
```
This pull request solves this issue and in the request handler you get a decoded/parsed JSON. Behaviour for other content types should be unaffected.
As it uses sync API, it only works above node >=0.12
=> Add gzip and deflate decoder for json content type

lib/common.js, tests/test_common.js, tests/test_intercept.js
Improves on error messaging as mentioned in #398. 
Error messages should now include header information & appear in format
```
{"method":"GET","url":"http://www.example.com:81/path/1","headers":{"cookie":"fiz=baz"},"body":"{\"foo\": \"bar\"}"}
```
**NOTE: NEEDS WORK**
I introduced unit tests for this feature, which are passing, but for a reason I have yet to determine seemingly unrelated _tests were failing on my local machine_ subsequent to my changes to the stringify function, without an obvious cause. I haven't spent a ton of time debugging, but since there's demand for this feature I wanted to get a PR up in case anyone would like to take a look and try running the tests :)
=> Feature: Better unmatched request error

lib/request_overrider.js, tests/test_intercept.js
This makes behavior consistent with the Node.js HTTP module
(https://github.com/nodejs/node/blob/v6.0.0/lib/_http_client.js#L541).
=> Fix this pointer on "socket" event

package.json
Test files shouldn't be covered. This skews the coverage percentage and can lead to a decreasing coverage in pull requests because of uncovered test lines.
=> Exclude test files from coverage reports

lib/common.js, tests/test_isomorphic_fetch.js
This adds a `toString()` in `matchStringOrRegexp` to fix the usage of `matchHeader` and `basicAuth` together with isomorphic fetch.
=> Fix isomorphic fetch usage with basicAuth/matchHeader

lib/interceptor.js, tests/test_intercept.js
If an interceptor has query parameters, requests with no query string must not be intercepted.
Fixes #610
=> Fix interceptor if query have no query strings

.gitignore, lib/request_overrider.js, package.json, tests/test_intercept.js
This PR fixed #754 and #739
There are two changes:
1. Set `socket.connecting` to `true` to allow `request` module creates timeout timer.
2. Emit `ClientRequest.connect` event after connection delay, just before sending response. Before modification, it emits too early and make `request` module clears the connection timeout timer.
=> Fix request timeout no working

.npmignore
I was looking at my node_modules folder and wondering why it's so big (it's not nock, it's babel again :( ) and found two big folders in this project using the excellent baobab.
I thought I'd say hi and send a PR
So, hi! And here's a PR :heart:
=> Add some big folders to .npmignore

lib/intercept.js, tests/test_intercept.js
This fixes #856 . Currently, calling `nock.cleanAll()` will clean up and prevent any interception of the mocks but calling `pendingMocks()` on any of the scopes continues to return the mocked paths.
This has been fixed by updating the scopes of interceptors before cleaning them up.
```javascript
var scope = nock('http://example.org');
scope.get('/somepath').reply(200);
nock.cleanAll();
scope.pendingMocks(); // will now return []
```
=> Fix for "nock.cleanAll() does not remove pending mocks from scopes #856"

lib/match_body.js, tests/test_body_match.js, tests/test_common.js
This fix contains a fix for multipart handling as already merged in #425. The tests had an error where `str1` aka `spec` was never run through `match_body.js`.
=> fix for the "fix matchBody for multipart requests #425"

package.json, tests/test_browserify.js
Skipping the browserify test for Node versions >7.9 to remedy #933, assuming this might be a [Zombie](https://github.com/assaf/zombie) issue, which is out of scope for me to fix.
=> Skip browserify test because zombie fails @7.10

.travis.yml, lib/common.js, lib/recorder.js, lib/request_overrider.js, package.json, tests/test_recorder.js
We are currently blocked from full support of Node 8 due to nock.  This is my attempt to get nock working on Node 8.  If someone can review and give me pointers, I am willing to finish this up.
There is one browserify test failing on Node 7 and 8, but it seems to have been there before this change.
=> Updates to unblock Node 8

tests/test_back.js
The failing test was checking that a call to `www.amazon.com` was returning data. This URL does not return any data any longer - changed it to one that does.
=> Fix for #947

README.md
=> document `nock.recorder.clear()`

lib/scope.js, tests/test_intercept.js
=> `nock.define()` ignores badheaders option

lib/recorder.js
Capturing and printing recorded results, using:
```js
nock.recorder.rec({
output_objects: true
});
```
resulted in `[Object Object]` being output to standard out.
A serialized JSON object would be output.
=> fix: logging recorded requests resulted in output of [Object Object]

lib/interceptor.js
Currently, matching logging does not include the method or path of the request.  I have added these to make debugging non-matches easier.
=> Improve Match Logging

README.md
I had a use case recently where I forgot to add the Content-Type to nock and it caused another process to interpret the response as empty. Might be useful to demonstrate use of HTTP headers in the README alongside replyWithFile, even though it's also described elsewhere.
=> Document replyWithFile using Content-Type header

lib/interceptor.js, tests/test_intercept.js
First commit is a failing test for https://github.com/node-nock/nock/pull/965
Second Commit Fixes https://github.com/node-nock/nock/issues/835
=> [Fix 835] allowUnmocked for regex host and route

lib/match_body.js, tests/test_body_match.js
=> Solves #920

lib/request_overrider.js, tests/test_abort.js
Fixes #882
When a request is aborted, "nock" emits an "abort"-error.
If the client reacts on that error by aborting the request (this is what
"popsicle" does), the code will end in an endless loop.
This commit makes that the the "abort"-code is only executed, if the
request has not already been aborted.
=> Do not abort a an already aborted request, do not emit an error twice

README.md
I noticed that the opening line of the documentation regarding disabling real HTTP requests was a little difficult to follow. I hope this sounds a little better.
=> Changed Real HTTP request documentation to be more readable

lib/intercept.js, tests/test_intercept.js
This is in line with [nodejs error codes](https://nodejs.org/api/all.html#errors_error_code
). I chose `ENETUNREACH` because it clearly defines the reason why the http request failed.
This helps testing when using an http request library that does retries as this isn't an error you would normally retry.
=> Add an error code to NetConnectNotAllowedError

lib/common.js, tests/test_common.js
The "mocking succeeds when mocked and specified request headers have falsy values" which I made for #966 was still failing when run with `{only: true}` :/ I really don’t trust the tests much right now
Anyway, this fixes it for good now, I hope
=> compare falsy header values & numbers correctly

lib/recorder.js, tests/test_recorder.js
This PR fixes an issue when using arrays inside a query string.
Prior to this change when using the following query string via superagent we get...
`.query({"foo":["bar","baz"]})`
The result is...
`.query({"foo":"baz"})`
Essentially the last value overrides any prior values due to the way the query string object is being formed. The fix is to simply use the `qs` library's `.parse` function which makes sense since the library is using `qs` elsewhere.
The result then becomes...
`.query({"foo":["bar","baz"]})`
Which now matches the superagent query input.
Resolves https://github.com/node-nock/nock/issues/896
=> Fix recording query strings, where value is an array

lib/request_overrider.js, tests/test_intercept.js
Backport of https://github.com/node-nock/nock/commit/50859e52fd86759f3215cdc3509c83d364b84cf5 from 9.0.x to 8.2.x. Fixes compatibility with Axios. Fixes #992.
=> Fix #992 Bind the socket event listener to the request object

lib/interceptor.js
closes #989
i didn't find any tests around log output, so i simply updated the log output. both changes are needed, one for when query params are defined, the other when no query is defined. i verified manually that each fix handles the appropriate case properly after the change.
=> Include `path` in the matching log output

lib/common.js, tests/test_common.js
Fixes `TypeError: Cannot read property 'match' of undefined` when `pattern` is a regex and `target` is undefined.
=> Fix matchStringOrRegexp TypeError

lib/match_body.js, tests/test_common.js
**Problem:**
If the matcher for the body is a function the new lines in the body should not be stripped.
Because the developer writing the test should know that there are newline in the body.
Also there are API which expect newlines in the body, with the stripping it's hard to write tests for these APIs.
**Solution:**
I just change the order within match_body.js. This way a function `spec` will be used first and only if the spec is not a function the body will be altered and the new lines will be removed.
**Changes:**
- One new test case added
- Code order in match_body changed
closes #533
=> fixing #533

lib/match_body.js, tests/test_body_match.js
Re-add support for matching body to query string regex
Fixes #1005 and #1004 
This was working before the recent change to body parser. 
From the docs:
```
The request body can be a string, a RegExp, a JSON object or a function.
var scope = nock('http://myapp.iriscouch.com')
.post('/users', /email=.?@gmail.com/gi)
.reply(201, {
ok: true,
id: '123ABC',
rev: '946B7D1C'
});
```
=> Fix body.exec is not a function

lib/interceptor.js, tests/test_intercept.js
Followup to https://github.com/node-nock/nock/pull/973
Failing test in commit 1
A combination of a regex that is reliant on query params + allow unmocked would fail. Fix is in commit 2 https://github.com/node-nock/nock/pull/1010/commits/424f0eda1790c98e3b1105988e633c27b9e40294
=> Added support for regex with query params

lib/match_body.js, package.json, tests/test_body_match.js
The querystring package does not stringify nested attributes of json object.
It'll broken regexp matching if request body contains complex json data.
```
> qs = require('querystring')
> qs.stringify({ a: { b: 1 } })
'a='
```
=> fix regexp on nested json object

lib/common.js, lib/interceptor.js, lib/recorder.js, tests/test_recorder.js
I stumbled upon a bug when trying to record and reuse a recording that was using query parameters with the `+` sign. The problem is that the recording, when generated using `generateRequestAndResponse`, [always sets `encodedQueryParams: true`](https://github.com/node-nock/nock/blob/master/lib/recorder.js#L126). When reusing those recordings, [the `+` sign is then interpreted as a space](https://github.com/node-nock/nock/blob/master/lib/common.js#L312), and so it is never able to reuse that recording for the same query.
I added a test to make sure that the query parameters are encoded when using `generateRequestAndResponse`, and tested that it does indeed allows to replay those requests when a `+` sign is in the query.
Thanks for reviewing!
=> fix: Encoding query parameters when recording to string.

lib/request_overrider.js, tests/test_https_allowunmocked.js
We must pass protocol [option](https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_http_request_options_callback) to the [ClientRequest constructor ](https://github.com/node-nock/nock/blob/master/lib/request_overrider.js#L258). By default, it uses `http:` [protocol](https://github.com/nodejs/node/blob/master/lib/_http_client.js#L112) but when we do https request our agent has `https:` protocol. If the protocol does not equal expected then the [error is thrown](https://github.com/nodejs/node/blob/master/lib/_http_client.js#L131)
=> Bug 976 expected https protocol

lib/request_overrider.js, tests/test_intercept.js
Slight change to the error message thrown comparing the header received with the header expected. The idea is that hopefully, it will help identify more quickly what exactly went wrong. The new error message will look something like this:
`Nock: No match for request {"method":"GET","url":"http://google.com/?num=1str=fou"} Got instead {"method":"GET","url":"http://google.com/?num=1str=fou@#"}`
closes #1018
=> fix: URLs Ending with Comma Cause "No match for HTTP request" Error (#1018)

lib/request_overrider.js, tests/test_intercept.js
The Node.js write and end methods take a callback as third argument; this pull request also adds them to the Nock interface.
Fixes #1046 and #1044.
=> Implement callback on req.write and req.end

README.md
Took me a while to figure out why my mocks weren't working.  It was because I had recording enabled, but I wasn't clear that it also disabled mocking.  Hopefully this will help avoid the problem for others.
=> Add extra warning about recording disabling mocks

tests/test_intercept.js
changing it to example.com/?unmocked fixes the problem. But I really don’t think it’s a good idea we rely on outside websites for our tests in the first place 🤔
=> example.com/unmocked no longer returns default page

lib/recorder.js, lib/scope.js, tests/test_recorder.js
The way nock currently implements the loading of previously recorded fixtures does not support proper binary responses, as nock cannot differentiate between a binary file encoded as hex string and a simple string. To work around that I've added a new flag to fixtures (`nockDef`): `responseIsBinary`.
I could not find a better workaround for it, but this works.
closes #1021, closes #1001, closes #524
=> Record & replay binary file response correctly

lib/interceptor.js, tests/test_intercept.js
I do not understand the implication of changing the condition with this commit, but this "fixes" the problem. My hope is that this is either enough to fix the issue or allow someone with a better understanding of what _.isRegExp(this.__nock_scopeKey) is doing to fix this. There didn't seem to be any tests that cover the condition, so I'm not sure how it's supposed to work.
fixes #1034
=> fix: Allow allowUnmocked = true and regexp paths to work (#1034)

lib/recorder.js
Our PhantomJS build currently fails because of `nock` with the following error message:
```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
SyntaxError: Unexpected token '}'
at /tmp/node_modules/nock/lib/recorder.js:82:0
```
This change fixes the build.
=> Fix usage under PhantomJS 2

README.md
=> Clarify request body matching on README

lib/match_body.js, tests/test_body_match.js
It's first step to resolving issue #1106.
I think, that this behaviour is good, but can be unexpected for long-time nock users. Maybe we need an option to enable this behaviour?
~~Also RegExp values are turning into strings. It's not good.~~ (Updated)
I can continue what I started if the whole approach is acceptable.
Review please @gr2m.
=> feat(match_body): urlencoded body matches not only string values

lib/common.js, tests/test_common.js
fixes https://github.com/node-nock/nock/issues/1121
main idea: `set-cookie` and `Set-Cookie` should merge into the same array
maybe apply `toLowerCase` to all "rawHeaders" entry?
which makes the expected return to have all lower-case keys
=> adding a failing test for issue#1121

lib/common.js, lib/interceptor.js, lib/recorder.js, lib/request_overrider.js, lib/socket.js, tests/test_common.js, tests/test_intercept.js, tests/test_isomorphic_fetch.js, tests/test_recorder.js, tests/test_s3.js
No longer throws DeprecationWarning as described in #1140 
Not sure whats up but fails the same tests as `master` branch so I assume that is okay?
https://nodejs.org/docs/latest/api/buffer.html#buffer_buffer_from_buffer_alloc_and_buffer_allocunsafe
=> fix(Buffer): update buffer constructors to use from and alloc

lib/common.js, lib/interceptor.js, lib/recorder.js, lib/request_overrider.js, lib/socket.js, tests/test_common.js, tests/test_intercept.js, tests/test_isomorphic_fetch.js, tests/test_recorder.js, tests/test_s3.js
This reverts commit e933b3a4a5b7ca598d789026978f718b5049fb92.
This restores compatibility with Node<4
=> Revert "refactor: update Buffer constructors to from and alloc (#1141)"

package.json
closes #1146, should help with https://github.com/node-nock/nock/pull/1145#issuecomment-395563855
=> chore(package): update restify-clients to version 2.2.0

lib/interceptor.js, tests/test_intercept.js, tests/test_recorder.js
I had to update the port numbers in the `test_recorder.py` because the test cases were failing with the `EADDRINUSE` error for port 8081.
=> fix(issue-1137): No match when basePath is regex and path is function

README.md, lib/request_overrider.js, tests/test_events.js
I am working on a testing scenario where I am running a method that then makes several requests. In the tests, I needed to later inspect the request body, but it did not appear to include a simple way to get the request body. If there is another way to do this, no worries, but this was helpful for me.
Example:
```javascript
const twitter = nock(/twitter\.com/).persist().post(/media\/upload/).reply(200);
const methods = {
'INIT': [],
'APPEND': [],
'FINALIZE': [],
'STATUS': []
};
twitter.on('request', (req, interceptor, body) => {
const parsed = querystring.parse(body);
if (parsed.command) {
methods[parsed.command].push(body);
}
});
return myMethod().then(() => {
expect(methods.INIT).to.have.lengthOf(1);
// ...
})
```
Not sure if this would be helpful (or better?) in the `replied` event? …
=> Updated the scope.request event emitter to include the request body

lib/request_overrider.js, tests/test_intercept.js
fixes https://github.com/nock/nock/issues/1156
Request overrider was using headers from options.
But some library don't set headers via options.
Use req.headers (retreived before in the same function) to ensure body is parse as JSON when header Content-Type=application/json
=> fix: request overrider checks req.headers to parse body as json

lib/scope.js
While going through the source code I noticed that the package 'util' provided by Node - the method _extend was used. This is deprecated since node v.6 and was never intended for the public API.
I replaced it with Object.assign instead as per the recommendation of Node.
[Deprecation notice](https://nodejs.org/api/util.html#util_util_extend_target_source)
=> fix: Replaced util._extend with Object.assign due to deprecation

CODE_OF_CONDUCT.md
I have changed the maintainer.io support email from `richard@maintainer.io` to `coc+nock@maintainer.io` in an attempt to make it more applicable in other CoCs, less tied to my own namespace, and to point out that emails which go to this email do not necessarily go to me, but to my team, which may at times include more than just a single perceived cis white male. Hopefully, this change will make it easier to email Maintainer as a third party in disputes.
=> docs(CODE_OF_CONDUCT.md): Change maintainer support email

README.md
And also the GitHub description, which previously did not include "for Node.js".
=> docs(README.md): Change description to match package.json

CHANGELOG.md
It was not immediately clear to me that the CHANGELOG was part of the GitHub releases. Adding this file will clear up that. However, it does add an extra file. We could include this in the CONTRIBUTING, or better, in the README, instead, if you like. I am suggesting this here as the CHANGELOG file is what I would naturally look for when I am looking for a CHANGELOG. However, I may be out of touch with modern development practices and this may be overoptimizing. What do we think?
=> docs: Add CHANGELOG file pointing to GitHub releases

README.md, lib/match_body.js, tests/test_body_match.js
When creating a mock, you can also pass in a buffer for an expected body.
The buffers are encoded as utf8 strings if applicable (if `common.isBinaryBuffer(...)` returns `false`), and otherwise, are hex encoded as they are on the [request client side](https://github.com/nock/nock/blob/f81fb6d/lib/request_overrider.js#L238).
This allows for matching against expected binary content like for Protobuf-based APIs, and goes along with the existing replies with buffers.
```js
// Example with compiled protobuf.js output.
const messages = require('./messages');
let incoming = messages.IncomingMessage.create({
foo: 1,
bar: 'test'
}).encode().finish();
let outgoing = messages.OutgoingMessage.create({
message: 'success!'
}).encode().finish();
nock('http://proto-service.io')
.post('/api/cool-endpoint', …
```
=> feat: encode an expected buffer the same way when matching as the client

README.md, lib/interceptor.js, tests/test_intercept.js
When setting up a mock, you can call `optionally()` to specify that the mock is __optional__, meaning that it won't be returned in `nock.pendingMocks()` and it won't affect the result of `nock.isDone()`.
You have to call `optionally()` before you call a method like `reply()` to specify the response, because at that point the mock is persisted and you can no longer touch it (that is to say, `reply()` returns the scope rather than the mock).
This part of Nock's API makes life painful if you want to have a mock which is configurable as either optional or required. The way that mocks are chained together makes your code long-winded and hard to read:
```js
const getLoginMock = ({ optional = false }) => {
const mock = nock('https://supercoolauthservice.com')
.post('/login');
if (optional) { …
```
=> feat: Allow optionally() to be called with a value, specifying if the mock should be optional

lib/request_overrider.js, lib/socket.js
I recently encountered the `socketDelay` bug noted in https://github.com/nock/nock/issues/1174 (at least, fairly sure).  More specifically, I observed breakage running my test suite on node versions `>=10.7.0`. 
https://github.com/nodejs/node/pull/21204 looks like an extremely likely upstream cause of the behavior I'm experiencing with nock.  It was [released](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md) in node `v10.7.0` so the timing fits as well. 
Notably, before that change, if a request's socket attribute was truthy and writeable, `req.setTimeout` would invoke `socket.setTimeout` without inspecting any connection state, like `socket.connecting` ([ref](https://github.com/nodejs/node/pull/21204/files#diff-e3bc37430eb078ccbafe3aa3b570c91aL720)).  Now, …
=> Set socket connecting state to always be false

CONTRIBUTING.md
This section should represent ways to help out as a contributor, and what we look for in maintainers. I tried to highlight the main things that community members can do to help out, and what the maintainers look for when we are thinking about having someone join the project. What do you think?
=> docs: Add a section on becoming a Maintainer

README.md
http://theoatmeal.com/comics/misspelling
=> docs: README.md typos (its / it's)

README.md, lib/intercept.js, tests/test_back.js, tests/test_intercept.js, tests/test_net_connect.js
I have improved the NetConnect section in the Readme, and edited the error
message that is thrown when dealing with disallowed connections to be a bit
more grammatical in my dialect of English.
This work started when I dove in a bit on #1187 (thanks, @danielb2).
=> Improve the NetConnect docs and error messages

README.md
Anchor for "Allow __unmocked__ requests on a mocked hostname" was broken
=> docs: Fix anchor in README

lib/scope.js, tests/test_back_filters.js
Fixes #1041. This is quite old issue however still only `filteringRequestBody` has applied on current version.
=> fix(#1041): apply filteringPath from nockBack before option

README.md
This PR is to show the explicit usage of the beforeFunc in nockback.  The correct syntax is in this issue https://github.com/nock/nock/issues/380 so I went ahead and updated the readme as well.
=> docs: show usage of beforeFunc in nockback

package.json
Without this change:
```
> nock@0.0.0-development pretest /Users/pnm/code/nock
> npm run -s lint
internal/modules/cjs/loader.js:582
throw err;
^
Error: Cannot find module 'acorn'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
at Function.Module._load (internal/modules/cjs/loader.js:506:25)
at Module.require (internal/modules/cjs/loader.js:636:17)
at require (internal/modules/cjs/helpers.js:20:18)
at Object.<anonymous> (/Users/pnm/code/nock/node_modules/acorn-jsx/index.js:8:15)
at Module._compile (internal/modules/cjs/loader.js:688:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
at Module.load (internal/modules/cjs/loader.js:598:32)
at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
at Function.Module._load …
```
=> test: Install missing dev dependency for linting

lib/intercept.js, lib/request_overrider.js
When unit testing, it is not uncommon to mock the clock. This includes controlling when setImmediate fires. By using global.setImmediate, we adhere to this expectation. This also avoids consumers having to mock the timers module.
Resolves #677
=> chore(setImmediate): use global.setImmediate instead of timers.setImmediate

package.json
we’ll need this for pre- and maintenance releases. Follow up for https://github.com/nock/nock/issues/1285
=> bump semantic-release to v16 beta

.travis.yml, CONTRIBUTING.md
=> build on branches for semantic-release preview/next/maintenance releases

lib/mixin.js
These two lines are not covered by code coverage. The function is called in one place, where it always has truthy arguments, so it seems simplest to remove this behavior.
=> fix(mixin): Remove dead code

tests/test_back.js
Ref https://github.com/nock/nock/pull/1298#issuecomment-448392497
=> test(test_back): Cover both of the ‘no fs’ code paths

package.json
=> fix: package.engines shows incorrect versions and is supposed to be an object

package.json
See https://docs.npmjs.com/files/package.json#engines
This is causing a validation error in Shields:
https://img.shields.io/npm/l/nock.svg
=> fix: package.engines is supposed to be an object

lib/intercept.js, lib/request_overrider.js, package-lock.json, package.json, tests/test_fake_timer.js, tests/test_intercept.js
replicate of the fix for #1334 for beta branch
=> Revert https://github.com/nock/nock/pull/1270 

tests/test_scope.js
The `persist()` is causing this to follow a different path than the one this was intended to cover.
=> test(Scope): Improve coverage on no-op Scope#remove test

package-lock.json, package.json
I imagine I was the one to add this. It shouldn't have been there! `eslint-plugin-prettier` is for integrating prettier errors into eslint, which is not the most convenient way to use it.
=> Rm lint dep we’re not using

lib/common.js
I found the library function we were looking for :)
We messed up on the semantics of this method in #1375. I think we should reverse the semantics of the method and started to fix that, though it's a somewhat involved diff so I decided to defer the refactor until we hit our coverage target.
=> refactor: Replace homegrown buffer compare with library method

lib/request_overrider.js
- `http.IncomingMessage` was added in Node v0.1.17. Since then it has always been truthy.
- `zlib.gunzipSync` and `zlib.deflateSync` were added in v0.11.12 and have been truthy since then.
=> refactor(request_overrider): Remove unreachable code

tests/test_intercept.js
This test was added in https://github.com/nock/nock/commit/1b5849ac391e81c464938e22d7577b8b3f23b724 which set `_headers` on an intercepted `req` object.
Presumably subsequently, `_headers` became a property on `http.OutgoingMessage`.
It was later deprecated:
https://nodejs.org/api/deprecations.html#deprecations_dep0066_outgoingmessage_headers_outgoingmessage_headernames
Suffice it to say that:
1. The assertion passes when run _without_ nock.
2. This test does not seem to any longer exercise any code from `nock`.
=> test: Remove a pointless test

lib/common.js, lib/recorder.js, tests/test_recorder.js
I also added a test to check for alternative ports.
Part of #1374.
=> tests: Add tests for lib/recorder.getScope

lib/intercept.js, lib/request_overrider.js
In Node, it’s valid to invoke `new ClientMessage()` with no options. However, in Nock, this causes a crash:
```
Cannot read property 'proto' of undefined
stack: |
Object.normalizeRequestOptions (lib/common.js:12:27)
interceptorsFor (lib/intercept.js:139:10)
new OverriddenClientRequest (lib/intercept.js:263:26)
Test.t (tests/test_request_overrider.js:20:8)
```
Fixing that does not seem like a high priority, so this provides a better error message, while also removing related unreachable code.
=> fix(intercept): Improve error message when `new ClientMessage()` is invoked with no options

lib/request_overrider.js, lib/socket.js, tests/test_intercept.js
`ClientMessage.socket` is an instance of our `socket` class. As that class’ constructor sets `authorized` to `true` on `https` requests, the code here that sets `response.socket.authorized` is pointless.
`ClientMessage.client` was deprecated in iojs 2.2 and per request/request#1615  but is still aliased: https://github.com/nodejs/node/blob/2e613a9c301165d121b19b86e382860323abc22f/lib/_http_incoming.js#L67
The old code, which sets `response.client.authorized`, is being replaced with new code which aliases `response.client`. This ensures that `response.client` and `response.socket` point to the same thing, which provides parity with a non-overridden request. This may help with compatibility with libraries which depend on that undocumented property, such as some very old versions of …
=> feat(request_overrider): Set `IncomingMessage.client` for parity with real requests

lib/request_overrider.js
- `response.headers` was added in Node v0.1.5 and `response.rawHeaders` in v0.11.6. They are truthy.
- `_headers` was deprecated, and replaced with `getHeader()`, `getHeaders()`, and `setHeader()`: https://nodejs.org/api/deprecations.html#deprecations_dep0066_outgoingmessage_headers_outgoingmessage_headernames
=> refactor(request_overrider): Remove dead code

CONTRIBUTING.md
We've had a couple PRs opened against `master` instead of `beta`. I hope this makes it clearer!
=> docs(CONTRIBUTING): Clarify that new PRs should be against beta

lib/interceptor.js, tests/test_intercept.js
~Previously, whenever you intercept a path with no leading slash nock will not resolve the URL correctly. This fixes the issue by adding a leading slash if required while creating an `Interceptor`.~
Given https://github.com/nock/nock/pull/1391#discussion_r250725610, we decided to make nock raise an error whenever the user forgets to add a leading slash into the intercepted path, instead of adding it itself.
Fixes #1259.
=> Throw error when leading slash is not present in path

CONTRIBUTING.md
Useful for helping others write tests. Note: I didn't know how to run the ToC command, so a second commit was added. Can we add a way for us to run the tocbot without needing to have more commits? Or is it not important?
=> docs: Add a note about running a single test

lib/intercept.js
The only time `key` is falsy is if we've gotten an `Interceptor` and it has a falsy `_key`. `_key` is set to a truthy value in the Interceptor constructor and doesn't appear to be set anywhere else.
Also, this behavior of emptying the array made no sense to begin with.
Ref #1404
=> refactor(intercept): Remove dead code for unreachable edge case

lib/intercept.js
This function is exported from this module, though it doesn't appear to be part of the public interface, and is only invoked here, from `activate()`. Activate makes the same check before calling this function.
=> refactor(intercept): Remove dead code

lib/common.js, lib/interceptor.js, tests/test_common.js
This came up while working on #1424. This code remains ugly, though it's apparent now why the `|| {}` assignment is needed.
=> refactor(common): Gently refactor headersArrayToObject

tests/test_recorder.js
I just had a built fail because of it:
https://travis-ci.org/nock/nock/jobs/496683359#L2610
=> Add TODO comment to remove request to example.com

package-lock.json, package.json, tests/test_basic_auth.js, tests/test_delay.js, tests/test_header_matching.js, tests/test_persist_optionally.js, tests/test_replies.js
1. Assert the expected argument is passed. (It's the correct argument, though not the expected type!)
2. When the function returns true, assert the request matches.
3. When the function returns false, assert the request doesn't match.
4. When the function returns false, assert the mock is not consumed.
5. I added copies of these tests for `matchHeader` called on the interceptor instead of the scope.
Test 4 uncovered an unexpected behavior in tap, which is that `t.rejects` causes our `afterEach` hook to fire – since it's implemented as a subtest.
Not knowing how to work around this, I replaced our uses of `t.rejects` with a promise-rejection assertion that does not rely on a subtest.
Ref: https://github.com/nock/nock/issues/1305#issuecomment-475912886 and tapjs/node-tap#525
This was …
=> test: Improve tests for header matching with function; adopt new promise-rejection assertion

lib/intercept.js, lib/interceptor.js, tests/test_header_matching.js
Currently, the header filter fails if there is not a `getHeader` method present on the `options` object. This sometimes appears to be the case. This is a simple node program written that should work as a repo
```typescript
import httpProxy from 'http-proxy';
import nock from 'nock';
nock('http://example.com')
.matchHeader('any-string', val => true)
.get('/hello'),
reply(200, 'goodbye');
let proxyServer = httpProxy.createProxyServer({
changeOrigin: true,
selfHandleResponse: false,
target: 'http://example.com',
});
proxyServer.listen(8080);
```
```bash
curl -X GET http://localhost:8080/hello
```
This change also makes the two checkHeader methods consistent. Where one previously respected functions and the other did not.
=> fix: Fix `.matchHeader()` with `allowUnmocked`

lib/scope.js, tests/test_define.js
Shockingly, `_.isNumber(NaN)` is `true` which means this conditional check didn’t even work as intended.
Testing error paths is important!
Ref #1404
=> fix(define): Throw error when legacy reply is in wrong format

lib/interceptor.js
I did a partial investigation into the host-matching issue. I can't say I got to the bottom of it. But I did learn a few things.
1. At the time this code was added, the recorder was changed to no longer by default record saved request headers.
2. The comment says nock sets these headers. Also [the readme says so](https://github.com/nock/nock/blob/dca678849a7fc0a779b2b9c49e416b4299cfebfb/README.md#specifying-request-headers). I am not completely sure what this means, nor why we do this.
3. The `setRequestHeaders` function seems to have something to do with this, but I don't completely understand why we're doing this here and in this particular way. https://github.com/nock/nock/blob/dca678849a7fc0a779b2b9c49e416b4299cfebfb/lib/request_overrider.js#L35-L61
4. The code is unreachable because …
=> test(intercept): Reference the issue

lib/scope.js
Several hours have been spent on this puzzling bit of uncovered code. I can’t remember what the last investigation revealed. It did not quite reach a conclusion nor can I find any notes about it.
I think this particular case is not worth investigating any further. Let’s keep the check (at least as long as this code is sitting around), and throw an error if it fails. We’ll find out soon enough if there is a use case where a non-string argument can reach this function.
=> refactor(scope): Replace unreachable conditional with an assertion

README.md
Identified as missing here https://github.com/nock/nock/issues/1514#issuecomment-488742980.
This option seems to have been added to better support how the
recorder saves and plays back. But as it is a valid, public option it
should be documented.
Tests already exist.
=> chore(docs): Add encodedQueryParams option to docs.

lib/interceptor.js, tests/test_intercept.js, tests/test_scope.js
Calling `filteringPath` on the intercept instance was broken as the
transform fn set on the scope had the wrong name.
Proxying to the Scope’s method allows for the regex version to work too.
The bulk of the changed lines come from moving the tests to their
appropriate file since the real logic acts on the Scope.
Found when looking at uncovered lines in Coveralls.
Side work, pulled out from #1520.
=> Bugfix Interceptor.filteringPath

tests/test_recorder.js
Adapted from @ctstone's work in #1231
Also ref #1229
=> test: add test for JSON-encoded strings stored by recorder

lib/request_overrider.js, tests/test_intercept.js
According to the docs, `req.end` can accept callback as a first argument. That's what `got` module does.
Closes #1509
```
request.end([data[, encoding]][, callback])
```
=> Support req.end with callback only

.travis.yml, lib/recorder.js, lib/request_overrider.js
=> fix: Fix `req.end(cb)` when recording in Node 12

lib/request_overrider.js, tests/test_request_overrider.js
Mocked requests were missing the 'method' property on them.
Added a testcase to the `test_request_overrider` testsuite.
=> feat(requestoverrider): Add method property to mocked requests

README.md
=> Add links between .persist() and .times() in readme

lib/request_overrider.js, tests/test_clientrequest.js, tests/test_content_encoding.js, tests/test_reply_function_async.js, tests/test_stream.js
This, along with another PR I have for headers, will take `lib/request_overrider.js` to 100% branch coverage. 
For #1404
=> Add tests to increase coverage of the Request Overrider.

.eslintrc.yml, lib/common.js, lib/recorder.js, lib/request_overrider.js, lib/scope.js, tests/test_abort.js, tests/test_allow_unmocked.js, tests/test_define.js, tests/test_delay.js, tests/test_intercept.js, tests/test_net_connect.js, tests/test_nock_lifecycle.js, tests/test_recorder.js
Removes most of the eslint overrides that had the "TODO These are included in standard and should be cleaned up and turned on."
- no-path-concat
- no-throw-literal
- handle-callback-err
- eqeqeq
- new-cap
- camelcase
Each rule is isolated in it's own commit to ease reviewing. 
The only setting I left in place was `no-deprecated-api`. There are two places where this rule is broken and each deserve their own PR.
- `tests/test_header_matching.js` makes use of the `domain` module, which has been deprecated since Node v4.0.0, to aid in asserting errors. That whole file needs to be refactored anyway to use `got`.
- `url.parse` was deprecated in Node v11.0.0 in favor of the `url.URL` constructor. This will require some careful work to change as POJOs that resemble the output of `url.parse` get …
=> Lint: Remove overrides.

README.md
Before v2.0, it was not possible to **not** filter on request bodies.
For [users wanting](https://github.com/nock/nock/issues/39) to match regardless of the request body, a [convention](https://github.com/nock/nock/commit/460aac919149fb190e910117c10c82f9d0e4c68e)
became the norm of using `filteringRequestBody` to modify the body into
a special string (`*`) then match against that specific string in the
Interceptor.
In more recent versions, the preferred way to not match request bodies
is to not provide a body argument when creating an Interceptor. This
updates the docs to reflect that.
=> docs: Remove unnecessary uses of filteringRequestBody.

lib/recorder.js, lib/scope.js, tests/test_define.js
Clarify and add test definitions bodies that are simply "*".
The investigation for this TODO also led to the creation of #1578, which has a description on the history of `*`.
---
Before v2.0, it was not possible to **not** filter on request bodies.
For [users wanting](https://github.com/nock/nock/issues/39) to match regardless of the request body, a [convention](https://github.com/nock/nock/commit/460aac919149fb190e910117c10c82f9d0e4c68e)
became the norm of using `filteringRequestBody` to modify the body into
a special string (`*`) then match against that specific string in the
Interceptor.
In more recent versions, the preferred way to not match request bodies
is to not provide a body argument when creating an Interceptor. This
updates the docs to reflect that.
=> refactor: special asterisk bodies in definitions.

lib/common.js, lib/scope.js, tests/test_header_matching.js
Adds a test to cover the exception case.
Going through the git history for this function, all the way back to
when it was added with 4048734a, I can't find a case where a non-object
input was valid.
Once PR # 1564 is merged in, this utility will only be called in two
places:
- Creating an Interceptor if the Scope was created with `options`
- When http.request is called with an `options` object
In both places, providing defined, but non-object values causes chaos.
If the value is a truthy, non-iterable then the header was ignored
during matching. For example, the following will match Interceptors as
if `reqheaders` had not been provided.
```js
nock('http://example.com', { reqheaders: 1 }).get('/').reply
```
However, if the value was provided as a non-plain object iterable, such
as an array …
=> Throw if headersFieldNamesToLowerCase is not provided an object.

lib/common.js, tests/test_common.js
For #1404
The changes for each of the three functions that were tested and/or refactored are broken up into separate commits to ease review.
=> test: Bring common.js up to 100% coverage

lib/request_overrider.js, tests/test_request_overrider.js
`ClientRequest.connection` is an alias for `ClientRequest.socket`.
https://nodejs.org/api/http.html#http_request_socket
https://github.com/nodejs/node/blob/master/lib/_http_client.js#L640-L641
`IncomingMessage.connection` is an alias for `IncomingMessage.socket`.
https://github.com/nodejs/node/blob/master/lib/_http_incoming.js#L44-L45
Adding `req.connection` and `res.connection` as a basic `EventEmitter` was to fix #74 when the `request` lib use to inspect the alias. [This is not the case anymore](https://github.com/request/request/search?q=connection+extension%3Ajs+-path%3Atests).
`res.connection` was [removed](b8c1bde2be58ee2378f8536a6732cb5e2ea98b33) a few years later to improve coverage.
=> bug: alias connection to socket.

.eslintrc.yml, lib/back.js, lib/intercept.js, lib/match_body.js, lib/scope.js, package-lock.json, package.json, tests/test_body_match.js, tests/test_net_connect.js
Supersedes #1592
ESLint offers a [migration guide](https://eslint.org/docs/user-guide/migrating-to-6.0.0) for their newest major release. There were two issues that kept nock from simply upgrading.
- The version of `eslint-plugin-import` listed in the `package-lock.json` was not compatible. The newest version of the plugin works and is within the range already defined in `package.json` so I simply performed lockfile maintenance (regenerating the lockfile from scratch).
- `eslint:recommended` was changed. The only new rule that really affected nock was [`no-prototype-builtins`](no-prototype-builtins).
I also noticed we still had some instances of the deprecated `assert.equal` in tests so I updated those to use the preferred `assert.strictEqual`.
=> refactor: update ESLint to 6.0.0

lib/back.js, tests/test_back_filters.js
- Change fixture filename to be different than the one used in
`test_back_2.js` to avoid race conditions.
- Update the server response to have higher resolution entropy.
- Minor refactoring and typos.
It's unclear which systems this flap is prevalent on, but on my macOS
Mojave it would error at least 10% of the time. I narrowed it down to
the synchronous file system calls not being 100% safe for race conditions
when two test suites were creating, updating and deleting the same file
in a short period of time.
=> test: fix flappy nock back test

lib/recorder.js, lib/request_overrider.js, tests/test_recorder.js, tests/test_request_overrider.js
Fixes #1549
The method now correctly accepts all the permutations allowed.
```js
request.end(data, encoding, callback)
request.end(data, callback)
request.end(data, encoding)
request.end(data)
request.end(callback)
request.end()
```
And a few tests were added to ensure all cases are explicitly covered.
=> fix: request.end accepted arguments

lib/recorder.js, package.json
Ref https://github.com/nock/nock/issues/1404#issuecomment-509347456
This leaves intact two missed coverage spots in `lib/recorder.js` which are being taken care of in #1588.
Also ref #1607
=> Add coverage ignores to recorder, and emit text report

lib/socket.js
it has been implemented in node.js 0.9.1 but it's seldomly used.
ref: https://nodejs.org/api/net.html#net_socket_unref
I came across this while mocking tests for a project using [apm-nodejs-http-client](https://github.com/elastic/apm-nodejs-http-client) [^](https://github.com/elastic/apm-nodejs-http-client/blob/fe9945ef8f96885802e029835cf3181ca2dd11b5/test/lib/utils.js#L33)
=> added noop method `unref` to Socket

lib/common.js, lib/interceptor.js, lib/recorder.js
For #1404
We were doing this logic in several places and not always getting good coverage. 
Adding a small utility DRYs it up.
=> refactor: add utility to identify non-standard ports

lib/request_overrider.js, lib/socket.js, tests/test_delay.js, tests/test_request_overrider.js
Changes the logic around socket events in the Request Overrider, which
had comments that correctly denoted how confusing the code was compared
to what it was trying to achieve.
Previous logic monkey patched the `EventEmitter.on` method on the request
to watch for an addition of a `socket` listener and then emitted related
events. This was added explicitly to fix issue 79 where Nock would hang
when Restify was the client.
This change takes a different approach and attempts to mimic what a non-
mocked request would do.
`ClientRequest` always emits a `socket` event after a socket is assigned
to the request https://nodejs.org/api/http.html#http_event_socket
Then the socket emits connect and secureConnect events.
Note that the approach would more real to life, and cleaner, if the
socket itself …
=> refactor(overrider): cleanup socket event logic

lib/recorder.js, tests/test_define.js, tests/test_intercept.js, tests/test_recorder.js
Fixes #1607 (assuming #1616 is merged in first)
Part of #1404 
While this work started out as just an effort to add coverage to recorder.js, I found/fixed a bug so I'm using the `fix` type.
There was a bug that kept request headers from being added to `matchHeader` lines in non-object outputs.
`enable_reqheaders_recording` was only having an affect if `output_objects` was also true, but headers were never being added despite that because it was looking for headers under the wrong attribute on the request.
A test was added to cover the flow of wanting the `matchHeader` as the other flow was already covered.
There are a couple other changes intertwined with the bug fix. It seemed cleaner to PR them together since it's all so tightly coupled. Things to keep in mind:
- …
=> fix(recorder): allow recording req headers when not outputting objects

lib/request_overrider.js, tests/test_request_overrider.js, tests/test_stream.js
Fixes https://github.com/nock/nock/issues/1493
https://nodejs.org/dist/latest-v10.x/docs/api/http.html#http_message_complete
=> fix: response.complete must be true after res.end

lib/interceptor.js
For #1404 
`Interceptor.match` is only called by the Request Overrider in the `end` function. 
Only the first call on line 245 ever uses the `body` arg.
https://github.com/nock/nock/blob/2c4edba933c996003c565f04ab8ce53c5df023aa/lib/request_overrider.js#L225-L253
Note that the logic block on lines 225-229 ensures that the `requestBody` variable is always a string.
Also, moved the call to `transformRequestBodyFunction` way down to just
before `matchBody` is called, just so it isn't unnecessarily called if
any of the non-body matches fail before it gets to that point.
=> refactor(interceptor): remove dead code for casting body to string

README.md, lib/interceptor.js, tests/test_allow_unmocked.js, tests/test_query.js
fixes: #1421
There was inconsistent behavior around how search params were handled
when they were provided as part of a URI string to new Interceptors.
The issue happen to come to light when `allowUnmocked` was set.
The fix normalizes the behavior by refactoring the constructor of
Interceptor to look for literal search params. If present, they're
stripped from the `path` attribute and set via the `query` method.
As part of the work, `Interceptor.query` was modified to accept
`URLSearchParams` instances as valid input.
=> fix: allow unmocked when providing literal search params.

lib/socket.js, tests/test_socketdelay.js
I'm not sure if this is the right approach.
Another option would be to send the coverage to Coveralls from Node 10
or 12. But that still may confuse devs when testing 8 locally.
@paulmelnikow ref a07b0bae8d6c7358274cd3129f276dda9389cff6
=> test(socket): add coverage for timeout without a callback

lib/interceptor.js, tests/test_query.js
Resolves #1623
BREAKING CHANGE: Providing a duplicate search parameter to the `query`
method throws an error instead of ignoring subsequent values.
=> feat(interceptor): duplicate query keys throw

lib/interceptor.js, tests/test_allow_unmocked_https.js, tests/test_query.js
Continuation of #1626
BREAKING CHANGE: Attempting to call `Interceptor.query` twice throws an error.
=> feat(interceptor): duplicate query calls throw

.travis.yml, README.md, lib/common.js, package.json
We've hit 100% coverage!
Coveralls is mostly useful for growing coverage over time. I think the text report is adequate for finding gaps in feature branches and preventing us from slipping. I don't think it's worth running Coveralls anymore.
I replaced the coverage badge with a static one!
Closes #1404
=> Advertise and enforce 100% coverage, drop Coveralls

lib/delayed_body.js
As the start of some modernization / stylistic updates, I started converting the `Foo.prototype`'s to ES6 classes.
=> refactor: Convert DelayedBody to a class

lib/common.js, lib/interceptor.js, lib/match_body.js, package-lock.json, package.json, tests/test_common.js, tests/test_complex_querystring.js, tests/test_query.js
Drop `deep-equal` and `qs` dependencies.
Replace `qs.parse` with `querystring.parse` from the std lib.
The main difference between the two being that `qs` "unpacks" nested
objects when the search keys use JSON path notation eg "foo[bar][0]".
This has no affect on URL encoded form bodies during matching because
we manually convert the notation to nested objects for comparison now,
which means users can now provide expectations in either form.
Similarly, when matching search params using a provided object, there
is no net effect. The only breaking change is when a user provides a
callback function to `.query()`.
Replace `deep-equal` with a custom utility function in common.js.
Doing so not only dropped a dependency, it also achieved a more generic
utility for our use case with less code. …
=>  refactor: overhaul body and query matching

README.md, lib/request_overrider.js, tests/test_reply_function_async.js
This is a POC for #1557 and is offered as an Option B to #1572. 
The difference between this change and #1572 is that this takes a hard line on how to handle errors in reply functions. It always emits an error (105fda4b7948a008626d189350b2e7c84c9c1869). 
I personally believe this is the right design long term but it does introduce a breaking change.
Using the example from the docs:
```js
const scope = nock('http://www.google.com')
.post('/echo')
.reply(201, (uri, requestBody, cb) => {
fs.readFile('cat-poems.txt', cb) // Error-first callback
})
```
Currently, if `readFile` errs, the request will succeed with a response that has a 500 status code.
To achieve the same affect, the code would have to be rewritten by the consumer to:
```js
const scope = nock('http://www.google.com') …
```
=> Async Reply functions (always emit errors)

lib/recorder.js
The `qs` dependency was removed, however, recorder.js retained usage of it. 
Replacing it with `querystring` from the std lib is sufficient.
Introduced: #1632
Fixes: #1651
Note that the output of `generateRequestAndResponse` will change for requests with search params, however, the net effect when that output is used will be the same.
=> bug(recorder): replace qs lib with native querystring

lib/request_overrider.js, tests/test_allow_unmocked_https.js
Fixes: #1422
The `allowUnmocked` option is processed in two places. Once in the
intercept when there are no interceptors that come close to matching
the request. And again in the overrider when there are interceptors
that partially match, eg just path, but don't completely match.
This fixes and explicitly tests the later case in the overrider by
making an HTTPS request for a path that has an interceptor but fails to
match the query constraint.
=> bug(overrider): unmocked HTTPS request with partial interceptor match

lib/request_overrider.js, lib/socket.js, tests/test_destroy.js
It adds the [destroy](https://nodejs.org/api/http.html#http_message_destroy_error) method to the response to manually terminate a connection and optionally raise an error captured from listeners bound to request `error` event.
As discussed in #1669 
---
I'm still not sure if this is enough, I took a look at [http_incoming](https://github.com/nodejs/node/blob/787378879acfb212ed4ff824bf9f767a24a5cb43/lib/_http_incoming.js#L104-L107) from node http core:
```js
IncomingMessage.prototype.destroy = function destroy(error) {
if (this.socket)
this.socket.destroy(error);
};
```
And from [http_client](https://github.com/nodejs/node/blob/787378879acfb212ed4ff824bf9f767a24a5cb43/lib/_http_client.js#L450-L456) also from node http core:
```js
if (ret instanceof Error) {
prepareError(ret, parser, d); …
```
=> Feat: Added response.destroy method

package.json
This doesn't add much value from Node's POV, since it can resolve it all
the same, however, some tools get confused.
[`index.js` is also the default](https://docs.npmjs.com/creating-a-package-json-file#default-values-extracted-from-the-current-directory) value for the field so it could be
removed, but it's probably for the best to be explicit.
Fixes: #1654
=> chore: add extension to main field in package.json

tests/test_intercept.js
Opening this pull request for a test case that will fail until #1108 is fixed. 
I tried digging deeper and what I found was that the /hello/planet interceptor is not in `interceptors` when `RequestOverrider` is finding a match.
=> Add test case for conflict between hostnames (#1108)

lib/common.js, lib/interceptor.js, lib/recorder.js, lib/scope.js, lib/socket.js, tests/test_request_overrider.js
There are no changes of functionality in this PR, just trivial stylistic changes.
- Adopt consistent function style (apart from no-block `const` arrow decls).
- Avoid assigning to variables when they are only reassigned moments later.
- Improve spacing of comments.
- Remove redundant comments.
- Name arguments to functions that take many parameters.
- Import URL and URLSearchParams using destructuring.
- Replace noop function props with empty methods.
- Move some var decls to immediately before first use.
=> style: Minor style improvements

types/index.d.ts, types/tests.ts
Fixes: #1694
From my testing, I haven't been able to find any negatives with using
`export =` and `declare` vs direct export when using TS 3+. Going
this route allows for consumers still using TS2 and/or not using
`esModuleInterop` to still utilize the bundled types.
Closes: #1684
I don't think the casing of the exported object makes a difference
either way, but using lowercase seems to fit with common usage (as a
function) better.
=> fix(types): use export = and declares

types/index.d.ts, types/tests.ts
Fixes: #1724
Closes: #1723
Updates the JSONish type using inspiration from the thread on adding a
JSON type to TS. https://github.com/Microsoft/TypeScript/issues/1897#issuecomment-338650717
This change does a couple sublet things:
- Adds `undefined` to scalar values allowed in arrays or as values in objects.
This allows for interfaces with optional keys to be passed in. ref #1723
- Splits out top-level array and objects into their interfaces so they could be used directly.
Allows enforcing non-arrays for `.query`.
- `RequestBodyMatcher` now extends the array and map types instead of the raw `DataMatcher`.
Allowing arrays fixes #1724.
This also ensures that booleans, numbers, and `null` are not considered valid.
=> fix(types): data matcher for body and query.

README.md
Hey,
As I understand `nock` usually used in dev environment so there is a little update for docs.
=> docs(README): Replace --save option

lib/interceptor.js
After getting an error in the interceptor, mentioning URL's need to start with a slash, it was difficult to find out which URL was causing the issue. With this change, since the URL is included in the error message, it's easier to troubleshoot the issue.
=> feat: improve error output by showing which URL caused the error

lib/intercepted_request_router.js
Passing the socket from the request to the `IncomingMessage` is what
happens in native Node. Using a dummy `EventEmitter` then tacking the
socket onto the response later is kludge from historical tech-debt that
can now safely be cleaned up.
=> refactor(router): pass socket to IncomingMessage constructor.

tests/test_allow_unmocked_https.js
This test was flaky on my machine.
I’ve also refactored to use async and the tap assertions a little more cleanly.
=> refactor(test_allow_unmocked_https): Avoid a hardcoded port

lib/intercept.js
This also renames the `scopes` property to `interceptors`, which is more appropriate since it holds instances of `Interceptor`.
=> refactor: Rewrite a gnarly nested loop

lib/interceptor.js, package-lock.json, tests/test_intercept.js
Added a check for filteringScope in the scope options as @paulmelnikow suggested. Also updated the two test which did not have the root path defined as this change will enforce this. To make the compatible with request like { hostname: 'example.test' } changed default value from { path = '' } to { path = '/' } in the interceptor class.
Fix #1730
=> feat: Throw errors for URL paths without leading slashes, which will never match

README.md, lib/common.js, lib/intercepted_request_router.js, lib/match_body.js, lib/playback_interceptor.js, lib/recorder.js, lib/scope.js, tests/test_common.js
In 9da400f98aa2d7fe06e813b01403877fed4f2065 – which isn’t linked to the PR for some reason –`isBinaryBuffer()` was given a better name `isUtf8Representable`. The rename should have also inverted the logic, as a so-called “binary buffer” was one that was _not_ representable in UTF-8.
This completes the refactor, replacing all references to “binary” with “utf8-representable”. That is, except the parameter to `nock.define()`, which is still using `responseIsBinary`.
That one would be a breaking change (or backward compatibility would need to be maintained).
=> refactor: Correct the inverted logic of isUtf8Representable

package.json, tests/test_request_overrider.js, tests/test_scope.js, tests/test_socketdelay.js, tests/test_stream.js, tests/test_url_encoding.js
This adds a few `describe()` blocks. I didn't put everything into `describe()`s, only the tests I was able to logically group.
=> refactor: Convert a few files to the Mocha DSL

tests/test_query.js
These tests needed rewriting in async which was a big job, so I updated the assertions along the way. It cleaned up nicely.
=> refactor: Rewrite test_query using got, async, and chai

types/index.d.ts
currentMode exists but isn't typed - https://github.com/nock/nock/blob/master/lib/back.js#L282
It's referenced in the docs here https://github.com/nock/nock#modes
=> feat: add type for Nock Back `currentMode`

tests/test_common.js
This came up in #1748. `test_common` is probably one good place to mention this.
It'd also be nice to write a longer summary of our test strategy and maybe add it to CONTRIBUTING.md, though this seems like a decent start.
=> docs: Mention strategy of testing common utility code

lib/back.js, package.json, tests/test_back.js
While I'm a big fan of Chai for expressive tests, it's basically
syntactic sugar over assertion errors. In this case, the only place
were using Chai, outside of tests, was in one function that preformed
a truthy check with a custom message.
=> refactor: remove chai as a prod dependency

lib/common.js, tests/test_request_overrider.js
Ref newrelic/node-newrelic#316
Thanks @kennethaasan for finding this fix!
Fix #1836
Closes #1853
=> fix: Correct behavior when other libraries override http.get and http.request

lib/intercepted_request_router.js, tests/test_socketdelay.js
The current implementation only supports `req.setTimeout`, but Node.js
allows for `options.timeout` to accomplish the same.
https://nodejs.org/docs/latest-v12.x/api/http.html#http_http_request_url_options_callback
=> fix(socketDelay): support options.timeout

lib/scope.js, tests/test_scope.js, types/tests.ts
Updates the types to properly reflect that a Scope can be created with
the output of `url.parse`. Previously, it denoted that it accepted a
`url.URL` instance. To clarify, tests were also added proving that one
works while the other throws an error.
This issue seems to be blocking the build of other PRs (https://github.com/nock/nock/pull/1878), probably because dtslint got a little smarter recently. 
https://github.com/nock/nock/pull/1692 may be enough to add `url.URL` support.
=> fix(types): Scope accepts legacy Url not WHATWG

index.js, package-lock.json, package.json
=> Greenkeeper/semantic release 17.0.2

lib/interceptor.js, tests/test_allow_unmocked.js
When an Interceptor was created with a comparator for the path, the
`matchOrigin` function was comparing the string equivalent of the function
instead of evaluating it.
I'm not a fan of the fact that the function `matchOrigin` is comparing the
pathname, but that's a refactor for another day.
Fixes: #1867
=> fix: allowMocked when using a callback for the path

tests/test_allow_unmocked.js, tests/test_allow_unmocked_https.js
Convert assertions to Chai, prefer await over callback when appropriate, and replace Mikeal's Request with Got.
All in the name of prepping for Mocha DSL (https://github.com/nock/nock/issues/1305).
=> refactor(test): Chai assert allow unmocked

tests/test_basic_auth.js, tests/test_delay.js, tests/test_header_matching.js, tests/test_intercept.js, tests/test_net_connect.js, tests/test_persist_optionally.js, tests/test_query.js, tests/test_repeating.js, tests/test_reply_function_async.js
As mentioned in https://github.com/nock/nock/pull/1889, it appears that `assertRejects` is not currently used correctly - the third parameter is the message that the assertion emits if it fails, not a matcher for the exception text.
This PR fixes all usages of `assertRejects` to correct expect on the error message. It might also be worth considering migrating to something like `chai-as-promised` for a more standard chai based approach.
[Runkit](https://runkit.com/embed/6ywp0lq4dfhr) with an example.
=> test: fix assertRejects usage

tests/test_allow_unmocked.js, tests/test_allow_unmocked_https.js
For: #1305
Because of the indention changes, reviewing this PR without whitespace is much easier:
https://github.com/nock/nock/pull/1894/files?w=1
=> refactor(test): use Mocha DSL for allow unmocked

.github/workflows/continuous-integration.yaml, package.json
=> Require Node 10+

README.md, lib/intercept.js, tests/test_net_connect.js, types/index.d.ts, types/tests.ts
Fixes https://github.com/nock/nock/issues/1861
I've also uncovered a bug in the usage of `assertRejects` - the third parameter is not used by the library to match on the error message, but rather the message to print when the expected rejection does not happen. I will create a separate PR to fix all usages of `assertRejects` in the project.
=> feat: allow passing a function to `enableNetConnect()`

.github/workflows/continuous-integration.yaml, README.md, index.js, lib/back.js, lib/common.js, lib/intercept.js, package-lock.json, package.json, tests/test_allow_unmocked.js, tests/test_allow_unmocked_https.js, tests/test_basic_auth.js, tests/test_body_match.js, tests/test_define.js, tests/test_intercept.js, tests/test_net_connect.js, tests/test_query.js, tests/test_recorder.js, tests/test_reply_function_async.js, tests/test_reply_function_sync.js, tests/test_scope.js, types/index.d.ts, types/tests.ts
Follow up to https://github.com/nock/nock/issues/1896\#issuecomment-586734273
This PR reverts the changes from these commits
- a275769 test: Update got to the latest version and fill in missing coverage (#1825)
- 566461b feat: allow passing a function to `enableNetConnect()` (#1889)
- 11c0542 Require Node 10+ (#1895)
- e04d61d Update mkdirp to the latest version 🚀 (#1857)
- 9379f09 Do not return the `nock` global from `cleanAll()` (#1872)
- 6c504c3 Drop support for String constructor (#1873)
=> Revert breaking changes from v11.9.0

lib/common.js, lib/interceptor.js, lib/scope.js
=> fix: Replace a few more uses of lodash

lib/back.js, package-lock.json, package.json
Now that we expect Node v10+, we can pass the `recursive` option to `fs.mkdir`.
Fixes #1913
=> chore: remove mkdirp

tests/setup.js, tests/test_request_overrider.js
CR [without whitespace](https://github.com/nock/nock/pull/1923/files?utf8=%E2%9C%93&diff=unified&w=1) still recommended.
=> refactor(test): Mocha DSL for request overrider

types/index.d.ts, types/tests.ts
This method does not exist and was added on accident.
Fixes: #1934
=> fix(types): remove inaccurate Scope.restore method

tests/test_destroy.js, tests/test_dynamic_mock.js
Also replaced `request` with `got` in the dynamic tests.
=> refactor(test): Chai assert destroy & dynamic mock

tests/test_delay.js
Also replaced remaining `request` calls to use `got`.
=> refactor(test): Chai assertions in delay tests

tests/test_destroy.js, tests/test_dynamic_mock.js, tests/test_reply_function_async.js
I moved the one test from 'dynamic' to `test_reply_function_async.js` since it was passing the callback as a second arg, then added a few tests to `test_dynamic_mock.js` to cover body and headers being optional.
=> refactor(test): Mocha DSL for destroy & dynamic mocks.

lib/scope.js, tests/test_define.js
BREAKING CHANGE: Skipping body matching using "*" is no longer supported.
Set the definition `body` to `undefined` instead.
This was deprecated in v11. https://github.com/nock/nock/pull/1579
=> chore: remove body matching using "*" using definitions

lib/common.js, lib/interceptor.js, lib/match_body.js, package-lock.json, package.json
- `isMap` was added to `util.types` in Node 10.0
https://nodejs.org/api/util.html#util_util_types_ismap_value
- `isPlainObject` and `mapValue` both came from LoDash's master branch, which is the pending v5.
Ref: #1285
=> refactor: replace LoDash isPlainObject, mapValues, and isMap

lib/intercepted_request_router.js, lib/playback_interceptor.js, lib/socket.js, tests/test_abort.js, tests/test_back.js, tests/test_client_request.js, tests/test_header_matching.js, tests/test_intercept.js, tests/test_request_overrider.js, tests/test_socket_delay.js, tests/test_stream.js
Nocks behavior around events and errors relating to aborting and ending requests has not lined up
with Node for while. I dug into an investigation of how it differs, if there were git commits/pull-requests explaining why they differ, and trying to answer the question of should Nock change to line up better.
The single largest deviation were the errors emitted around aborting or already aborted requests.
Emitting an error on abort was added to fix issue #439.
The conversation talks about how Node emits an error post abort.
> ... in practice the `http` module does emit an `ECONNRESET` error after aborting. ... - Jan 7, 2016
However, this is only true between the 'socket' and 'response' events.
Otherwise calling abort does not emit an error of any kind.
Determining exactly what Nock should …
=> fix(router): bring behavior of `abort()` inline with native Node

README.md, lib/intercept.js, lib/intercepted_request_router.js, lib/interceptor.js, lib/playback_interceptor.js, lib/scope.js, tests/test_logging.js, types/index.d.ts, types/tests.ts
Consolidates the behavior around debugging and logging to exclusively use [`debug`](https://github.com/visionmedia/debug).
The use of `scope.log(console.log)` was problematic and confusing for consumers as that
appeared to be the correct approach when debugging unless they found the correct section in the README.
The use of the logger vs directly using `debug` in the core of Nock was inconsistent, especially when matching.
Now any failure to match a request will be directed to `debug` and if a single Interceptor is in context,
the namespace in the log will include the host from the Scope. This allows for filtering of logs to stdout
as well as differentiating colors from `debug`, when enabled.
BREAKING CHANGE:  `Scope.log` has been removed. Use the `debug` library when debugging failed …
=> feature: remove Scope.log in favor of more debug

tests/test_delay.js
The tests are all generally the same, there was a bit of reorganization. 
The biggest change was the addition of some tests on `delay` that asserts various call signatures proxied correctly to `delayConnection` and `delayBody`. Then most of the tests that were calling `delay` now call the underlying `delay*` method directly. 
As with the other PRs that added Mocha `describe` blocks, viewing this PR [w/o whitespace](https://github.com/nock/nock/pull/1967/files?w=1) is recommended.
=> refactor(test): Mocha DSL for delays

lib/intercepted_request_router.js, lib/playback_interceptor.js, lib/socket.js, tests/test_request_overrider.js
- Stop monkey patching `abort` on the overridden `ClientRequest`.
- Stop prematurely associating the socket with the request.
- Prefer `destroy` instead of emitting an error when appropriate.
----
Overall I think this change is great because it brings the overridden `ClientRequest` even more inline with native Node.
There were two external changes that prompted this update: First [`ClientRequest.abort`](https://nodejs.org/docs/latest-v14.x/api/http.html#http_request_abort) was deprecated in Node 14.1 in favor of [`ClientRequest.destroy`](https://nodejs.org/docs/latest-v14.x/api/http.html#http_request_destroy_error). And second Got v11 began handling _only the first_ error emitted by a `ClientRequest`, which caused subsequent errors to bubble up as unhandled when using the client lib.
A …
=> fix(ClientRequest): Use native `abort` and `destroy`

CHANGELOG.md, migration_guides/migrating_to_10.md, migration_guides/migrating_to_11.md, migration_guides/migrating_to_12.md, migration_guides/migrating_to_13.md
Mostly just copy/pasted from release notes.
They could probably use some love with the help of community feedback, but it's a solid start.
Closes https://github.com/nock/nock/issues/2003.
=> chore(docs): Add migration guides.

README.md
It seems when Prettier was updated on `master`, the linter didn't run and update the README file with the new preferences.
This is why https://github.com/nock/nock/pull/1989 has a conflict apparently. 
Mostly commas and whitespace inside the code blocks of the docs.
=> chore: lint docs

.github/workflows/continuous-delivery.yaml, .github/workflows/continuous-integration.yaml, CONTRIBUTING.md, package.json
fixes #2012. After merging, use https://github.com/gr2m/octokit-plugin-rename-branch to update the branch, pull requests, and repository settings. 
But lets wait for v13 to be released, to avoid merge conflicts with the current work on `beta` +@paulmelnikow
=> build: replace master with main

README.md
`.reply` is a method of interceptor and not a method of scope
=> docs: fix wrong typing

lib/intercepted_request_router.js, lib/playback_interceptor.js, tests/test_abort.js, tests/test_intercept_parallel.js
When an request is matched to an Interceptor, mark it consumed immediately so
that similar requests made in parallel don't get matched incorrectly.
This changes the behavior of aborted requests slightly.
Previously, an Interceptor was marked consumed just prior to the "response" event.
Now it will be marked consumed just prior to the "finished" event.
The change can only be noticed if a request is aborted while in a "finished" listener.
There might be some debate on whether this is a braking change or a bug fix, but I'm inclined to release this as a patch considering v13 was just published. 
Fixes: #1937 
fyi @marian-r & @gurpreetatwal
=> fix(intercept): mark Interceptors consumed immediately

tests/test_delay.js
Allows duration assertions in the delay tests to pass if the observed time is just shy of the expected duration.
The related tests have been inconsistent with failing for what is thought to be race-conditions in the event loop.
Close: #2045
=> test(delay): ease assertions on delayed time.

lib/common.js, tests/test_common.js
Updates the `dataEqual` utility and underlying `deepEqual` recursive functions to treat explicit and implicit `undefined` object values as equal.
Also ensures that `expand` is only called on top-level data if they're plain objects, thus avoiding accidentally equating an object and any array if the object's keys happen to be integers.
Fixes: #2048
=> fix: data comparison with undefined object values

tests/test_basic_auth.js, tests/test_body_match.js, tests/test_define.js
I wrapped some tests in `describe` scopes, which indented all the nested tests. Viewing the change-set [without whitespace](https://github.com/nock/nock/pull/2070/files?w=1) is easier.
=> refactor(test): Mocha DSL for basic auth, body match, and define

README.md
=> docs: fix invalid code blocks in readme examples

lib/common.js, tests/test_intercept.js
When matching via a regexp instance, consistently test the entire target string.
Sets the `lastIndex` to zero for cases where the `global` flag is set and the regexp instance has been tested previously.
fixes: #2134
=> fix(intercept): handle global flags during regexp matching

lib/recorder.js, tests/test_recorder.js
Because the default output of the recorder uses single quotes, any such
quotes in the path would generate invalid Javascript.
I would prefer to use backticks, but went with escaping the single quote as the former would create a lot of unnecessary diffs for consumers commiting the output to version control (😉 @koerbcm).
Fixes: #2136
=> fix(recorder): escape single quotes in path of default output

lib/common.js, lib/intercepted_request_router.js, lib/playback_interceptor.js, tests/test_destroy.js, tests/test_nock_off.js
Node, as of 14.1, started migrating the Client Request terminology from
`aborted` to `destroyed`. In order to supported our current Node version
support, 10.x+, we need to check both flags. Nock was already doing this
in the router, but not during playback.
Identified from https://github.com/nock/nock/issues/2146
=> fix(playback): consistently check for `destroyed` attribute

lib/recorder.js, tests/test_recorder.js
Per [Node docs](https://nodejs.org/api/http.html#http_class_http_clientrequest),
> If no `'response'` handler is added, then the response will be entirely discarded. However, if a `'response'` event handler is added, then the data from the response object must be consumed, either by calling `response.read()` whenever there is a `'readable'` event, or by adding a `'data'` handler, or by calling the `.resume()` method. Until the data is consumed, the `'end'` event will not fire. Also, until the data is read it will consume memory that can eventually lead to a 'process out of memory' error.
However, when the Recorder was enabled, Nock would sometimes resume the response stream after monky-patching the `push` methods. This doesn't align with the goal of being consistent with native Node. And …
=> fix(recorder): don't automatically resume the response

package-lock.json, package.json, tests/test_fake_timer.js, tests/test_intercept.js
There were three tests simply using `superagent`, but not testing anything Nock related, so they were removed.
Two tests were using `request`, but were easily converted to `got`.
One test was testing an issue related to `request` strictSSL. The underlying issue was discovered, commented, and the test updated to use `https` instead.
And one test ("test request timeout option") wasn't actually testing anything Nock related, so it was removed.
Closes: #1777
=> chore(test) update/remove client specific tests

lib/interceptor.js, tests/test_intercept.js
=> fix(interceptor): don't require leading slash if Scope has a base pathname

.github/workflows/continuous-integration.yaml, lib/socket.js, tests/test_common.js, tests/test_socket.js
Node v16 flags seems to have changed.
closes #2199
=> feat: node 16 compatibility

README.md
- Remove "inactive" Dependabot badge
The readme has a Dependabot badge, that says that Dependabot is not working.
This is not true, as you do have Dependabot, just the GitHub native one.
GitHub native Dependabot doesn't have a functioning badge from GitHub themselves.
You could take a look at shields.io to create your own Dependabot badge and put that in the README.
There's an issue that asks for Dependabot to provide a working badge here: https://github.com/dependabot/dependabot-core/issues/1912
=> docs(readme): remove Dependabot badge

tests/test_reply_function_sync.js
=> Test reply function returning array with body object

types/index.d.ts
I noticed that the type for `Interceptor.optionally()` was missing the optional `flag` parameter. This PR fixes that.
=> fix(types): add missing argument to optionally()

lib/interceptor.js, tests/test_reply_with_file.js
- The first commit fixes an issue that caused the last request to hang when using a combination of `.times()` and `.replyWithFile()` - the counter was being decremented too early, which meant the `if` on the next line didn't pass and the last request didn't get a fresh `body`
- The second commit fixes a resource leak - because a stream is created [here](https://github.com/nock/nock/blob/eb742c20367e7b149ed63d4ffd14f8676222fdc0/lib/interceptor.js#L196) when calling `.replyWithFile()`, it should be consumed on the first call, and a new one should only be created [here](https://github.com/nock/nock/blob/eb742c20367e7b149ed63d4ffd14f8676222fdc0/lib/interceptor.js#L450) on the 2nd call.
The added test catches both of these issues.
=> fix(interceptor): don't hang, don't leak resources

README.md
This pull request adds an async/await example for the nock back functionality.
=> docs: add async/await example for nock back

.github/workflows/continuous-delivery.yaml, .github/workflows/continuous-integration.yaml
`actions/setup-node@v2` has dependency caching built into it, so this PR has been opened to simplify the caching process.
References:
* https://github.com/actions/setup-node#caching-packages-dependencies
=> Simplify dependency caching in CI/CD workflows

README.md
The fact that `removeInterceptor` works on some chains and doesn't work on other chains is very confusing because it means that existing code may break while the behavior is getting only extended (opposit to modified). Also, because documentation is not giving a clear difference on what chain methods returns what type of values. There are a bunch of issues on it:
https://github.com/nock/nock/issues/1822
https://github.com/nock/nock/issues/1117
https://github.com/nock/nock/issues/600
=> docs: add note on removeInterceptor usage

README.md, lib/back.js, package.json, tests/test_back.js
=> Added Update mode

types/index.d.ts
Included `'update'` in the `BackMode` union, following [the introduction of the update mode](//github.com/nock/nock/pull/2241).
=> fix(type): add `update` type for record mode

lib/interceptor.js, tests/test_allow_unmocked.js
=> Fix `allowUnmocked` not working w/ regex host + request body match (fixes #2276)

rfcs/rfc-001.md
inadvertantly -> inadvertently
=> docs(RFC): fix typo in rfc-001.md

package-lock.json, package.json, types/tslint.json
Same tool, DefinitelyTypes simply moved the project into their monorepo.
I did attempt to move away from dtslint all together, in favor of ESLint, which is preferred for proper Typescript projects. However, ESLint still lacks a lot of functionality for only declaration files and tests, like Nock has. So dtslint is still the way to go (until we migrate Nock to TS 😄  ).
=> chore(deps-dev): migrate dtslint to @definitelytyped/dtslint

lib/intercepted_request_router.js, lib/playback_interceptor.js, tests/test_delay.js
=> fix: delay when timeout is on the Agent

lib/common.js, lib/match_body.js, package-lock.json, package.json
Listing `lodash` as a prod dependency has a few advantages over the single func dep we were using.
Primarily, when a security vulnerability is patched in LoDash, those changes don't get published to individual function libs anymore.
The most recent example being the prototype pollution that was patched in 4.17.16.
That particular vulnerability didn't effect Nock because of our usage, however, Nock does show up as having a vulnerability because of it which is a pain for consumers. It also creates a future problem where the next patch could affect Nock more directly.
https://github.com/nock/nock/discussions/2279
It should be noted that LoDash itself discourages the use of these single function libs: https://lodash.com/per-method-packages
This changes also removes the vendor-izing of two …
=> fix(dep): migrate from lodash.set to lodash.

package-lock.json, package.json
Reverts nock/nock#2364
Got 12.x is ESM only, so we need to stay on 11.x until Nock starts supporting ESM too.
=> Revert "chore(deps-dev): bump got from 11.8.3 to 12.1.0"

.eslintrc.yml, lib/intercepted_request_router.js, tests/test_request_overrider.js
Hi, i found an issue with `InterceptedRequestRouter.handleWrite`:
`Http.ClientRequest.write()` can be invoked with a callback and no encoding, currently the code expected the callback to be the 3rd argument so if invoked the callback was never called.
BTW: this is my first contribution ever, so If I'm doing something wrong let me know
=> fix: `InterceptedRequestRouter.handleWrite` arity issue

README.md, lib/scope.js, tests/test_scope.js
This closes #2435 
I could not find a beta or next branch, so my changes were made against main. Please advise if I am missing something.
=> feat: add support for WHATWG URLs

README.md
axios stopped exporting the adapters (you will get `Cannot find module 'axios/lib/adapters/http'` errors) but you can now specify the adapter as a string.
=> fix axios adapter docs

README.md
This was added with #1711 but [has changed with axios v1](https://github.com/axios/axios/pull/5277)
=> fix(README): Update axios example

README.md, lib/intercept.js, tests/test_persist_optionally.js
Currently, if you do:
```
nock(..).get('/').reply(200).persist();
nock(..).get('/').reply(400); // this will never get called
```
The second interceptor won't get called ever.
But sometimes in tests (queue for examples), I want to do:
```
beforeAll(() => {
// some default behaviour
nock(..).get('/').reply(200).persist();
});
test('should ...', () => {
// test specific scenario for this same endpoint above
nock(..).get('/').reply(400)
})
```
I find a workaround using the body matcher function:
```
const createInterceptor = () => {
nock(..).get('/', () => { 
createInterceptor(); 
return true; 
})
.reply(200)
}
```
Which pushes the interceptor to the end of the queue (`interceptors` array) and mimics the wanted behavior but is slower and way less elegant.
P.S: I'll add tests and …
=> Push persisted interceptors to the end instead of ignore on remove

lib/intercept.js, tests/test_remove_interceptor.js
If you agree with the general solution, I'll add a proper test and fix the current tests.
Fix #2418
=> fix: `nock.removeInterceptor` can remove the wrong Intercept

README.md, lib/intercept.js, tests/test_persist_optionally.js
This reverts commit 8aab603f2b884f49618fbfdcc3c9529cccdc8975.  See #2500
=> fix: revert #2350 (Push persisted interceptors to the end instead of ignore on remove)

README.md
This had my team questioning our sanity for a good while, hoping to save future devs some time. :smile:
=> docs: add rawHeaders in mock docs

tests/test_common.js
I checked it now properly.
For some reason parseInt transformed the minor and patch to NaN.
There is no node 16.2.1, so we dont need to check the patch version. 
16.2.0 was still using the old error text. 16.3.0 was using the new error text.
=> test: improve node16 check in test

types/index.d.ts
The ambient type in `index.d.ts` does not match the actual call signature of the [filteringRequestBody](https://github.com/nock/nock/blob/main/lib/interceptor.js#L363)
This fixes it.
=> fix(typescript): `filteringBodyRequest`

README.md, lib/back.js, tests/test_back.js, types/index.d.ts
When TDDing using Nock Back you're kind of in a Chicken-and-Egg situation.  You want to be able to verify the external calls you need to make - but you don't know the exact nature of those external calls.   This lets you list the interceptors created in a given fixture to make sure all the ones that you expect are there.
By itself, this functions as a negative expectation - like I can verify that certain calls do NOT happen in the fixture.  When paired with `assertScopesFinished` this can be used to verify the complete set of calls in the fixture.  For instance I have a fairly complex HTTP interactor that synchronizes a local data store with a remote one.  I know how many calls this takes - and I know that if the scopes in the fixture complete then my interaction worked.
But if I need to …
=> feat: add `context.query()` to nock back

README.md, lib/scope.js, tests/got/test_scope.js
This pull request introduces a new method `Scope#clone()` to the `Scope`. This method allows creating a new `Scope` with the same `basePath` and `scope options`.
This is particularly useful when we cannot wait for all requests to complete, and we want to check if the requests have been fulfilled using the `isDone()` method.
Here is a simple usage example:
```javascript
describe('Example', () => {
const baseScope = nock('http://example.test')
it('GET scope is done', async () => {
const get = baseScope.clone().get('/').reply(200)
await got('http://example.test/')
expect(get.isDone()).to.be.true()
})
it('POST scope is done', async () => {
const post = baseScope.clone().post('/').reply(200)
await got.post('http://example.test/')
expect(post.isDone()).to.be.true()
})
})
```
=> feat: add `Scope#clone()` method

.github/workflows/continuous-integration.yaml, lib/common.js, lib/intercept.js, package-lock.json, package.json, tests_jest/memory_leak.spec.js
Just importing nock in a Jest test is enough to have a memory leak.
Fix for #2358
=> fix: fix memory leak when using nock with jest

.github/workflows/continuous-integration.yaml
in preparation of #2580 @mikicho
=> ci(test): use a single `test` job that we can require, independent of test matrix

.github/workflows/continuous-integration.yaml, lib/common.js, lib/create_response.js, lib/intercept.js, tests/test_fetch.js
BREAKING CHANGE: drop support for Node < 18
Fetch support.
1. Solves the urgent need for fetch support.
2. Although I think it's working as expected, I believe we should consider this as experimental until we see it working properly.
3. Recording is not supported, yet(?). Workaround can be found [here](https://github.com/nock/nock/issues/2397#issuecomment-1924424258).
4. I believe that we should keep working on switching the 'backend' to use 'mswjs/interceptors'., [here is why](https://github.com/nock/nock/pull/2517#:~:text=edited-,Why%3F,-Decompose%20interception%20and).
@gr2m WDYT?
CC @kettanaito
=> feat: native fetch mocking

.github/workflows/continuous-integration.yaml
In the package.json engines field it is specified that `"node": ">= 10.13"` which means version 20 is included 😄
=> ci: add node 20 in ci

lib/intercept.js, tests/got/test_nock_lifecycle.js
The `interceptorScopes()` function is used by `activeMocks()` and `pendingMocks()` to retrieve the list of all scopes. That list is built by concatenating the scopes of every interceptor. When multiple interceptors are registered on the same scope, the scope will be returned multiple times, causing `activeMocks()` and `pendingMocks()` to include duplicates.
This PR fixes the issue by ensuring there is no duplicate returned by `interceptorScopes()`.
Fixes #2352 (and #600, which also reported this issue)
=> fix: remove duplicates from `activeMocks()` and `pendingMocks()`

lib/interceptor.js, tests/got/test_query.js
closes https://github.com/nock/nock/issues/2342
@gr2m I'm a bit puzzled here. In the example, it seems like we support this, but we have (an old) test that specifically forbids string as an argument.
Anyway, I think we should support string.
=> fix: support literal query string

lib/create_response.js, tests/test_fetch.js
Fix https://github.com/nock/nock/issues/2397#issuecomment-1941125165
=> fix: fetch response status text

.eslintrc.yml, lib/create_response.js, package-lock.json, package.json, tests/test_fetch.js
fixes https://github.com/nock/nock/issues/2397#issuecomment-1961177318
This is a pretty naive solution that doesn't support more decoders easily (or multiple decoders at all), but I'm not expecting it in streams and such. 
Improvements are welcome.
=> fix: fetch support compressed responses

tests/got/test_request_overrider.js
=> chore: improve coverage of socket.js

lib/interceptor.js, tests/got/test_reply_with_file.js
When using `replyWithFile`, a ReadStream is immediately created wih the file path. When the mock is hit, another ReadStream is created immediately if the interceptor is configured to be set again or if its scope has `_persist` set. When calling `nock.removeInterceptor`, the ReadStream isn't closed. 
As a result, it's not possible to delete the folder where the file exists on Windows unless implementing a workaround like multiple `fs.rm` calls.
This PR removes the eager `fs.createReadStream` call when setting up the interceptor and instead configures the route to create 
the stream lazily, in a callback invoked when intercepting a call. There is no longer any need for `replyWithFile`-related logic in `Interceptor#markConsumed()`.
I also added an extra test for `replyWithFile` + …
=> fix: call `fs.createReadStream` lazily

lib/match_body.js, tests/got/test_reply_body.js, tests/test_common.js
The original lodash implementation of `mapValues` is a pure function that doesn't modify the object in place.
The new implementation is causing issues in test cases where the same object is used for the nock response and for validation. 
Here's an example of a test that broke when attempting to use the beta
```typescript
describe('#patch', () => {
it('can patch data locally', async () => {
const patchBody = {name: 'test', id: 1234};
nock(baseUrl)
.patch('/', patchBody)
.reply(200, patchBody);
// client#patch uses URL encoding
const response = await client.patch('/', patchBody);
should(response.body).eql(patchBody); // breaks
should(response.statusCode).eql(200);
should(nock.isDone()).eql(true);
});
});
```
=> fix: mapValues should not update the object in place

.github/workflows/continuous-integration.yaml
macos latest is using arm64 (M1!) and node 10, 12 and 14 were not compiled for that. 
So we exclude these cases from the test matrix...
=> ci: exclude nodejs 10, 12 and 14 tests running on macos

lib/common.js, tests/test_common.js
This fixes the memory leaks described in #2771 by first removing the unused `setInterval` spy, and then augmenting the `setTimer` and `setImmediate` spies to delete the strong references after the respective callback has been executed. Since the code base does not use any `clearTimeout` / `clearImmediate` calls, intercepting those for deletion from the Set is not required.
Closes #2771.
=> fix: memory leaks due to timer references outliving the timers

lib/common.js, tests/test_common.js
Simply backports the fix for #2771 to the main branch / v13. Should be worth it & low risk enough I think.
=> fix(backport): memory leaks due to timer references outliving the timers (#2773)

types/index.d.ts
This PR fixes a TypeScript discrepancy where the docs (and source code) say nock back's `afterRecord` function may also return a `string`, but the typings only allow for `Definition[]`.
=> fix(types): return type of BackOptions.afterRecord

package-lock.json, package.json
The @mswjs/interceptors package has a few bugfixes over the past 5 days that fix an issue my team was experiencing (https://github.com/mswjs/interceptors/issues/635). I'd like to bump the package in the beta branch to adopt these fixes.
=> fix(deps): bump `@mswjs/interceptors` to `^0.35.6`

.github/workflows/fix-formatting.yaml
Hi! Joyce here from Google's Open Source Security Team ([GOSST](https://opensource.googleblog.com/2023/04/googles-open-source-security-upstream-team-one-year-later.html)).  I've found a small fix to prevent script injection attacks in your GitHub workflows, PTL.
- parse `github.head_ref` into an environment variable before use (to prevent script injection).
You can see further explanation about this kind of threat in this blogpost [Keeping your GitHub Actions and workflows secure Part 2: Untrusted input](https://securitylab.github.com/resources/github-actions-untrusted-input/).
Let me know if you have any questions!
=> Fix: GitHub workflow script injection

.nycrc.yml, tests/test_fetch.js
Node.js did not backport the compression order fix to versions 18 and 20, so the test passes for version 22 (with the correct order) but fails for versions 18 and 20.
Because it currently blocks all builds, let's skip this test until the fix is fully deployed across all supported versions. A fix in the this pull request: https://github.com/nock/nock/pull/2827
=> chore(tests): skip failing test

.nycrc.yml, lib/recorder.js, tests/got/test_recorder.js
closes #2836 
We unintentionally created a listener for each request instead of a single listener for all requests. As a result, `mswjs/interceptors` invoked the same listener multiple times with the same `response` object. Then, we attempted to read its body twice and encountered the error. 
We use `listener.on` instead of `listener.once`. Also, I removed the unnecessary `request` listener.
Regarding the coverage, this is a small difference, and I plan to fix it back to 100% in my `cleanup` branch
=> fix(recorder): response body accessed multiple times in parallel requests

README.md
Examples for `removeInterceptor` can be read ambiguously, as if not defining params makes them work for all types of those params, when the code is written to instead default. https://github.com/nock/nock/blob/26fb02550dbd303f51da39655400cbe5b037d8d3/lib/intercept.js#L224
=> Update readme examples for removeInterceptor

.eslintrc.yml, README.md, lib/common.js, tests/got/test_fake_timer.js, tests/got/test_reply_headers.js, tests/test_fake_timers.js, tests_jest/test_fake_timers.spec.js
Make it work with `sinon` and `jest` fake timers. Fixes #2200
Importing `timers` instead of using the global ones would still not work for `jest`
=> fix: address timeout issue with mocked timers

README.md, lib/handle-request.js, lib/interceptor.js, tests/got/test_events.js, types/index.d.ts, types/tests.ts
https://github.com/nock/nock/issues/1413
Add reasons argument for `no match` event
```js
nock.emitter.on('no match', (req, interceptorResults) => {
console.log('Request did not match any interceptors:', req.url)
if (interceptorResults && interceptorResults.length > 0) {
interceptorResults.forEach(({ interceptor, reasons }) => {
console.log('Interceptor:', interceptor.method, interceptor.basePath + interceptor.path)
console.log('Reasons:', reasons)
})
}
})
```
The callback receives two parameters:
- `req` - The request object that didn't match
- `interceptorResults` - An array of objects containing detailed information about each interceptor that was tested
Each interceptor result object contains:
- `interceptor` - The interceptor that was tested against the request
- `reasons` - An array …
=> feat: add no match reasons
