README.md, lib/match_body.js, tests/test_intercept.js
Hey there, 
Thanks for the great library.  
This PR adds the ability to filter POST bodies dynamically using a callback function, as requested in #246.    Callback gets the body, converted to json if possible, and match succeeds based on the return value.  
Tests included and passing.
zeev
=> Post function spec

README.md
Only made 1 change in README.md:
1) Update the LICENSE to include the latest year as a year-range.
No other changes were made.
=> Update info in readme

README.md
=> improve the readability of README for filteringRequestBody

lib/request_overrider.js, lib/scope.js, tests/test_intercept.js
Allows you to mock/simulate an error on request.
=> Mocking Network Errors

README.md, lib/common.js, lib/scope.js, tests/test_common.js, tests/test_intercept.js
=> feature: fail when specified bad header is present

lib/scope.js
As I was testing for body params, I had hard time figuring out what it was actually sent. So I just added a few more things to print out.
=> Add more output for "bodies don't match"

README.md, lib/request_overrider.js, tests/test_intercept.js
=> replyWithError allows json response

README.md
Added runnable snippet for nock.back
=> (readme) nock.back example

README.md, lib/scope.js, tests/test_intercept.js, tests/test_recorder.js
Added candidate request body arg to filteringRequestBody
=> Fixed filteringRequestBody not working on recorded nocks

lib/recorder.js
I believe this addresses https://github.com/pgte/nock/issues/353
=> propagate data events the same way we propagate readable events

.istanbul.yml, .travis.yml, lib/intercept.js, lib/request_overrider.js, package.json, tests/browserify-public/browserify-bundle.js, tests/browserify-public/index.html, tests/fixtures/browserify-script.js, tests/test.js, tests/test_browserify.js
=> Browserify

lib/request_overrider.js, lib/scope.js, package.json, tests/browserify-public/browserify-bundle.js, tests/test.js, tests/test_isomorphic_fetch.js
Trying to fix #399, making it work with isomorphic-fetch.
=> isomorphic fetch

README.md
Maybe it's just my brain, but this took awhile for me to understand what needed to be set and how. Adding an example.
=> Adding example for debug environment variable

README.md, lib/scope.js, tests/test_intercept.js
Related to https://github.com/pgte/nock/issues/347.
Not sure how it would play with https://github.com/pgte/nock/pull/433, but I think we could use the `matchStringOrRegexp` method to also accept/handle functions
=> [feature] allow specifying path using regex

README.md, lib/match_body.js, tests/test.js, tests/test_body_match.js
I'm using this feature to hide my password in "nock" data. Would you consider to add this feature?
=> [feature] allow matching body with RegExp

lib/common.js, lib/request_overrider.js, tests/test_intercept.js
for https://github.com/pgte/nock/issues/344
=> parse requestBody if it is JSON content.

README.md, lib/common.js, lib/scope.js, package.json, tests/test.js, tests/test_complex_querystring.js
I found this issue https://github.com/pgte/nock/issues/376,  and feels it might be a good get-started-task to get my hands wet with open-source project, so I did this diff,  please let me know if it would work.  
@pgte @adborden
=> support complex GET query based the behavior of request module.

lib/common.js, lib/delayed_body.js, lib/interceptor.js, lib/request_overrider.js
There are three isStream functions. this PR move them to common.js.
=> Move isStream to the common lib.

README.md
Hey all, I keep running into issues cleaning up after nock and having tests conflict with each other. I proposed the localhost changes before and you all were gracious in accepting them. Reasoning here is to get a good example of best practices on an `afterEach`. If that could be split out into it's own section, "Testing with Nock" that could be neat too. Thanks for the work on this project it's great.
=> Add clean all to example about being done with the test

README.md, lib/interceptor.js, lib/request_overrider.js, tests/test_intercept.js
fix issue  https://github.com/pgte/nock/issues/192
=> add a new api delayBody() and update the syntax of delay().

lib/interceptor.js, tests/test_intercept.js
I'm not sure if this is the best fix for the issue, but this fixes #473.
Also not sure if I'm supposed to check in `tests/browserify-public/browserify-bundle.js` as well. If necessary, I can add to PR.
=> fix key when interceptor path is specified with callback

lib/request_overrider.js, tests/browserify-public/browserify-bundle.js, tests/test_intercept.js
This addresses a bug discussed in #489. CI should confirm, but all tests are passing on my machine:
=> Add support for full callback `reply()`.

README.md, lib/back.js, tests/test_back_2.js
Closes #487.
I haven't committed the browserify bundle.
=> Add ability to pass options to recorder from nock back

README.md, lib/interceptor.js, tests/browserify-public/browserify-bundle.js, tests/test_intercept.js
query accept a function to determine if the query is matched
=> query accept a function to determine if the query is matched

lib/request_overrider.js, package.json, tests/browserify-public/browserify-bundle.js, tests/test_back.js
- 2 tests depend on request's to Amazon statusCode. It's 301 now, but we expected only 200 and 302.
- Nock couldn't start with Node v0.10 because of lodash update. I've changed version for lodash
- Test `goes to internet even when no nockBacks are running` couldn't stop with Node v.0.10 before I've added the listener for res.data event
- lib/request_overrider.js contains a symbol with code `160`. I replaced it to space.
=> Fix some broken tests

lib/scope.js
Hi,
Not sure if you already have plans for supporting OPTIONS method but i thought i'd create a pull request since its pretty simple.
Thanks!
-abdul
=> Support http OPTIONS method

package.json
Add myself to the contributors in package.json 🛩
=> Add Ian WS to contrib

lib/common.js, tests/test_common.js
Fixes #818 
Would like to add a test asserting full intercept cycle works but don't have time ATM. Have tested manually and it works.
=> Bug 818 multiple set cookie

lib/common.js
=> Bug #827 Defensive coding around target

.gitignore, lib/request_overrider.js, package.json, tests/test_intercept.js
Reverts node-nock/nock#802
Created bugs (see #839)
=> Revert "Fix request timeout no working"

.travis.yml, package.json, tests/bin/install_sub_deps, tests/versioned/common.js, tests/versioned/got-latest/package.json, tests/versioned/got-latest/test.tap.js, tests/versioned/popsicle-latest/package.json, tests/versioned/popsicle-latest/test.tap.js, tests/versioned/request-latest/package.json, tests/versioned/request-latest/test.tap.js
Adds versioned tests, so we can defend against regressions specific an HTTP client.
=> Feature #832: Versioned tests

lib/match_body.js, tests/test_body_match.js
This reverts commit 8333e3aef1e79dc2ed96dca819124f4a18f1af4d, reversing
changes made to 30881e2a72dbb950e771f912c5f9ddbcb91c0acd.
I've received reports that v9.0.11 is breaking tests.
=> Revert "Merge branch 'fasterize-fix_match_body'"

lib/interceptor.js, tests/test_intercept.js
=> match headers with falsy values

README.md
it`s clone #958 because fork of #958 has been deleted
=> docs(README.md) - fix info about mocking

README.md, lib/back.js, tests/test_back.js
Return a promise when a nock back work function is not specified.
=> Promisify nock back

lib/back.js
Thanks for the useful library!
=> nockBack.setMode: Improve error message

README.md
I think that was an issue, feel free to close if that was intentional
=> Minor change in example code `scope(` => `var scope = nock(`

lib/intercept.js, tests/test_intercept.js
=> Fix allowUnmocked when last interceptor was removed.

README.md
* Rephrases a sentence.
* Adds punctuation.
* Corrects two typographical errors in the example.
Thanks for making an awesome library! 😄
=> Improve Nock Back documentation

lib/interceptor.js
follow up for https://github.com/node-nock/nock/pull/973/files#r140647611
=> match headers with falsy values (again)

.travis.yml, package.json
=> semantic-release setup

README.md
@gr2m Please review.
PR to fix Issue #997 
PR contains documentation update for:
1. restore()
2. activate()
3. isActive()
=> enhancement(readme): Documentation Update for activate, isActive, restore methods.

lib/common.js, lib/interceptor.js, tests/test_intercept.js
=> Fix for #1003. Correctly parse request without specified path

README.md
Proposing documentation for "stop recording" feature, closes https://github.com/node-nock/nock/issues/659
=> Simple proposal of documentation for stop recording

README.md, lib/scope.js, tests/test_intercept.js
=> feat: stop persisting a persistent nock.

lib/match_body.js, tests/test_body_match.js
as discussed here https://github.com/node-nock/nock/issues/1051
=> Test for array like params in a application/x-www-form-urlencoded 

tests/test_back.js
=> remove airplane dependency for 'tests/test_back#L154'

tests/test_back.js
=> test: remove airplane dependency for "tests/test_back#L137"

tests/test_back.js
=> Remove airplane dependency from "tests/test_back.js#L188"

tests/test_back.js
=> Remove airplane dependency from "tests/test_back.js#L235"

tests/test_back.js
=> Remove airplane dependency from "tests/test_back.js#L261"

tests/test_back_2.js
=> Remove airplane dependency from "test_back_2.js"

tests/test_back.js
Fixes #1092 Ref #1077 
I'm really not good with tests :sweat_smile:, please review carefully.
@gr2m
=> test: remove airplace dependency from tests/test_back.js#313

tests/test_intercept.js
=> [WIP] Remove airplane dependency from "test_intercept.js"

lib/interceptor.js, tests/test_intercept.js
=>  fix(#1171): When matching the path by function, also check the HTTP method.

lib/interceptor.js, tests/test_intercept.js
=> fix(issue-1076): allowUnmocked: true + regexp host = interception fail

package.json
=> chore(package): update needle to version 2.2.2

.github/ISSUE_TEMPLATE/01_bug_report.md, .github/ISSUE_TEMPLATE/02_feature_request.md, .github/ISSUE_TEMPLATE/03_support.md, .github/ISSUE_TEMPLATE/04_thanks.md
I think that will make the templates work!
=> fix issue templates

.github/ISSUE_TEMPLATE/01_bug_report.md, .github/ISSUE_TEMPLATE/02_feature_request.md, .github/ISSUE_TEMPLATE/03_support.md, .github/ISSUE_TEMPLATE/04_thanks.md
Just suggestions – Let me know what you think :)
=> ISSUE TEMPLATES: minor adjustments

CONTRIBUTING.md
=> docs: Add release process

tests/test_intercept.js
Two tests to make #1170 clearer.
=> test: Add two tests for reply cbs #1170

.github/stale.yml
Ping @RichardLitt – especially check how you like the stale comment. I want to convey / be transparent about that there is only so much we can do as volunteers (or very limited hours for maintainers.io)
once merged, install https://github.com/apps/stale.
=> Stale: initial configuration

.github/lock.yml
Review, merge and install #1217 first.
After merge, install https://github.com/apps/lock.
Ping @RichardLitt
=> lock app – initial configuration

.travis.yml, lib/common.js, lib/interceptor.js, lib/recorder.js, lib/request_overrider.js, lib/socket.js, tests/test_common.js, tests/test_intercept.js, tests/test_isomorphic_fetch.js, tests/test_recorder.js, tests/test_s3.js
Node 4 is no longer maintained since April 1, 2018:
https://github.com/nodejs/Release#end-of-life-releases
=> Drop support for Node 4

.travis.yml, package.json
=> coverage setup

README.md
this should make this table easier to maintain, we don’t need to change it each time we release a new breaking version
=> README: Node version support

tests/test_https_allowunmocked.js, tests/test_intercept.js, tests/test_nock_off.js, tests/test_recorder.js
=> Add  comment to all tests that still use  setting, resolves #1232

package.json
=> update debug to version 4.1.0

CONTRIBUTING.md
Related to #1217 and #1218. What do you think, @gr2m?
=> docs: Add note about GitHub Apps

README.md
=> Renamed recorder .reset to .clear

tests/test_intercept.js
Also ref: #1077
Turns out there aren't any more of these, so this fixes #1272.
=> Fix #1271 for test_intercept.js

tests/test_intercept.js
This adds server capabality to allow pass throughts for a couple of intercept tests. See #1077.
=> tests: passthrough 1077

tests/test_intercept.js
=> test(test_intercept.js): Test enableNetConnect without AIRPLANE

tests/test_intercept.js
After studying this test for a good hour with @RichardLitt and @jlilja, we determined that it wasn’t asserting anything useful. There are other tests of `reqheaders` and we were unable to infer what this was intending to test. So, remove this one.
Add clarifying comments in other tests we studied along the way.
Ref #1077
=> test(test_intercept.js): Remove pointless reqheaders test

tests/test_recorder.js
Should be good to go. See #1077.
=> test(test_recorder.js): Fix records test

tests/test_recorder.js
=> test(test_recorder): De-airplane remaining recorder tests

tests/test_abort.js
I thought I would start working my way through the test files and trying to clean them up, as a precursor to expanding coverage.
=> test(test_abort): Improve style + readability

.coveralls.yml, package.json
I also removed the `COVERALLS_REPO_TOKEN` environmant variable from Travis. I hope this will all work now as expected
=> remove obsolete coveralls configuration

.travis.yml
=> run release stage on [Version].x, next, beta branches

.eslintrc.yml, package.json, tests/test_basic_auth.js
See discussion: https://github.com/nock/nock/pull/1288#issuecomment-447697842
Also depends on: https://github.com/nock/nock/issues/1285#issuecomment-447696139
~~Probably this will need to target the new `beta` branch?~~
**Added:** Updated to target `beta`. Build should be green after #1299 is merged.
=> test(test_basic_auth): Rewrite using got + async/await

lib/back.js, lib/interceptor.js, lib/request_overrider.js
https://lgtm.com/projects/g/nock/nock/alerts/?mode=list
Everything else is ASI-related and better dealt with automatically (#1300).
=> fix: Fix some errors detected by LGTM

package.json
=> update semantic-release to beta.13

.travis.yml
follow up https://github.com/nock/nock/pull/1311#issuecomment-448680505
=> run prettier on update

lib/intercept.js, lib/request_overrider.js, package.json, tests/test_fake_timer.js
fixes #1334 
Forced pushed the branch to get Travis status on both commits.
=> Revert https://github.com/nock/nock/pull/1270

.travis.yml
See https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#caching-with-npm
=> Travis: cache: npm

.gitignore, package-lock.json
Per @gr2m the issue with Greenkeeper has been resolved and the lockfile can now be checked in. This should speed up our builds.
=> chore: Check in lockfile

tests/test_intercept.js
This is the test that kept failing yesterday.
=> test(test_intercept): Make delay+replyWithError test more reliable

package-lock.json, package.json
closes https://github.com/nock/nock/issues/1345 (I hope)
=> update semantic-release to latest beta

.travis.yml
=> Travis: run coverage on each build, not only on release

lib/common.js, lib/delayed_body.js, lib/intercept.js, lib/interceptor.js, lib/match_body.js, lib/recorder.js, lib/request_overrider.js, tests/test_common.js
This is the result of live triage with @gr2m and @jlilja: https://github.com/nock/nock/issues/1374#issuecomment-453344862
=> refactor: Rename a function and add todo comments

CONTRIBUTING.md, tests/test_nock_off.js
Close #1077.
This comment doesn't make sense to me and I'm not clear what needs to happen with this code:
https://github.com/nock/nock/blob/26954a7ed6747161c5ca1c557f0bf40ab59e7b6e/tests/test_back.js#L59-L94
=> docs(CONTRIBUTING): Remove traces of airplane mode

tests/test_back.js
=> test(test_back): Update last AIRPLANE comment

package.json
=> Remove markdown-toc

tests/test_define.js
=> docs: spelling error

tests/test_abort.js, tests/test_back.js, tests/test_basic_auth.js, tests/test_body_match.js, tests/test_common.js, tests/test_complex_querystring.js, tests/test_content_encoding.js, tests/test_dynamic_mock.js, tests/test_encode_querystring.js, tests/test_events.js, tests/test_fake_timer.js, tests/test_gzip_request.js, tests/test_intercept.js, tests/test_isomorphic_fetch.js, tests/test_net_connect.js, tests/test_redirects.js, tests/test_remove_interceptor.js, tests/test_socketdelay.js, tests/test_timeout.js, tests/test_url_encoding.js
Sorry about the delay. Here's the work so far. :) There is still tests that needs a local web server. But I guess it'll be easier to do that in another PR to get this one out into the beta branch.
Reference to ticket: #1351
=> Partially changing all test request's domains

lib/intercept.js, tests/test_remove_interceptor.js
=> refactor: Remove dead code, improve coverage in removeInterceptor

lib/intercept.js, tests/test_intercept.js
This brings `intercept.js` to 100%.
=> test(intercept): Cover nock resets during request

lib/socket.js, tests/test_socketdelay.js
=> fix(socket): When Socket#setTimeout gets a callback, should still emit

lib/interceptor.js, tests/test_intercept.js
=> test(interceptor): Cover no 'fs'

lib/recorder.js
Unable to find a way to trigger the conditionals. See #1404 for reasoning why I took on this test.
=> refactor: remove cruft

lib/recorder.js, tests/test_recorder.js
=> refactor: Remove unnecessary conditional, add test for undefined data

package-lock.json, package.json
=> Greenkeeper/superagent 5.0.2

CONTRIBUTING.md
Saw these questions in the Community Project board and endeavored to answer them myself. https://github.com/nock/nock/projects/3
=> docs: Add some FAQ questions

README.md
Just some minor things I noticed as I was reading the docs.
Great project and documentation!
=> minor typo fixes and grammatical changes

package-lock.json, package.json
=> Update tap to 13.0.3

tests/got_client.js, tests/test_allow_unmocked.js, tests/test_allow_unmocked_https.js, tests/test_basic_auth.js, tests/test_complex_querystring.js, tests/test_content_encoding.js, tests/test_default_reply_headers.js, tests/test_define.js, tests/test_delay.js, tests/test_header_matching.js, tests/test_intercept.js, tests/test_logging.js, tests/test_net_connect.js, tests/test_nock_lifecycle.js, tests/test_persist_optionally.js, tests/test_recorder.js, tests/test_redirects.js, tests/test_remove_interceptor.js, tests/test_reply_body.js, tests/test_reply_function_async.js, tests/test_reply_function_sync.js, tests/test_reply_headers.js, tests/test_reply_with_file.js, tests/test_stream.js
=> chore(tests): Disable got automatic retries which cause confusing behavior

lib/request_overrider.js
I worked on this file quite a bit since this comment was written. At this point the remaining work can be broken out into separate, manageable-seeming todos.
Ref #1404
=> chore(request_overrider): Update coverage TODOs

tests/test_intercept.js, tests/test_reply_function_async.js, tests/test_reply_function_sync.js
=> chore: Correct sorting of two tests

tests/test_intercept.js
=> test: Add test of DELETE request

README.md, lib/request_overrider.js, tests/test_reply_headers.js
=> Clarify that header function receives the response body

lib/interceptor.js, tests/test_reply_body.js
Fixes missing coverage for line added in #1520.
=> Add test to cover invalid reply status codes.

CONTRIBUTING.md
Closes https://github.com/nock/nock/issues/1453.
=> docs: Add note about OpenCollective bot

tests/test_allow_unmocked.js, tests/test_default_reply_headers.js, tests/test_delay.js, tests/test_events.js
=> test: Some hostname cleanup

lib/interceptor.js, tests/test_header_matching.js
For #1404
Add tests for the success, reject, and ignore cases.
=> test(interceptor): special Host header matching logic

lib/scope.js
Exact same logic, just consolidates the code using some newer JS.
=> refactor: Scope.pendingMocks

tests/test_define.js, tests/test_header_matching.js, tests/test_nock_lifecycle.js, tests/test_persist_optionally.js, tests/test_request_overrider.js
=> Clean up some more hostnames in tests

lib/socket.js
=> refactor: Convert Socket to a class

lib/scope.js
=> refactor: Convert Scope to a class

tests/test_common.js, tests/test_events.js, tests/test_intercept.js, tests/test_recorder.js, tests/test_reply_function_async.js, tests/test_reply_function_sync.js
=> test: change tests to use test domain

lib/intercept.js, lib/interceptor.js, lib/recorder.js
This PR is primarily a [refactor for the Recorders arguments](https://github.com/nock/nock/commit/cb4541b11ab7179879f489c810b3f3922b659860).
I also had a grab bag of other trivial refactors in my stashes that I've included. It seemed a little heavy to PR each of them separately, but I have committed them separately. If anyone prefers more PRs I'll happily split them out.
=> refactor: default options on recorder, remove dead code

lib/common.js, tests/test_reply_function_sync.js
Fixes #1642
Identified by @alexlitel
=> bug:  handle content-type request headers when arrays

README.md, tests/test_nock_lifecycle.js
Diff will clean up after #1646 is merged.
Closes #1042
=>  test: Clarify that cleanAll removes persistent mocks

package-lock.json, package.json
=> chore(dep): remove unneeded dev dep acron

tests/test_recorder.js
=> refactor: Fix two tests that don't work on an airplane

lib/back.js, lib/common.js, lib/intercept.js, lib/interceptor.js, lib/match_body.js, lib/request_overrider.js, lib/scope.js, tests/test_common.js
For: #1285
No logic changes, just making use of newer JS.
=> refactor: replace some lodash usage with native

README.md
=> docs: Add "Common issues" section documenting got automatic retrying

tests/test_net_connect.js
=> refactor: Refactor net connect tests

package.json, tests/fixtures/goodRequest.json, tests/test_back.js
=> refactor: Remove the last of the real hostnames

types/index.d.ts, types/tests.ts
=> fix(types): DataMatcher to allow valid JSON scalars.

README.md
Hi Nock community,
I would like to add back the knowledge of `axios` in Readme. Thanks `Nock` team. It is a very powerful testing package.
https://github.com/nock/nock/issues/699#issuecomment-272708264
Best,
Alpha
=> ADD: axios example

lib/interceptor.js, lib/playback_interceptor.js, lib/request_overrider.js
See discussion at https://github.com/nock/nock/pull/1712#discussion_r323528780
Closes #1502
=> refactor: Remove unnecessary getHeader() function

lib/playback_interceptor.js, lib/request_overrider.js
Ref #1718 and discussion at https://github.com/nock/nock/pull/1712#discussion_r323528780.
=> refactor: Avoid unnecessary call to setRequestHeaders after matching

lib/interceptor.js, tests/test_query.js
Remove repeated "already" in error message.
=> chore: Fix error message

lib/intercepted_request_router.js, lib/socket.js, tests/test_intercept.js, tests/test_request_overrider.js
fixes: #1643
https://nodejs.org/docs/latest-v10.x/api/net.html#net_class_net_socket
=> feature(socket): add missing Socket attributes

tests/test_url_encoding.js
Ref https://github.com/nock/nock/issues/1305#issuecomment-544878116
=> refactor: chai assertions for test_url_encoding

package-lock.json, package.json, tests/cleanup_after_each.js, tests/setup.js, tests/test_abort.js, tests/test_logging.js
Ref https://github.com/nock/nock/issues/1305#issuecomment-544878116
I thought I would get the ball rolling with just a single file.
=> test: chai assertions for abort tests

tests/test_reply_body.js, tests/test_reply_function_async.js, tests/test_reply_function_sync.js, tests/test_reply_headers.js, tests/test_reply_with_error.js, tests/test_reply_with_file.js
This adds a fair amount of nesting to these tests. Nesting is a mixed bag. It makes the tests a little harder to work with visually, so that's a downside. Though it also helps to clarify the specific behaviors being tested, and makes it much easier to reason about the collection of behaviors as a whole.
=> refactor: Mocha DSL for test_reply_*

tests/test_recorder.js
Oof, this file is rough. This makes it just a little bit better.
=> refactor: chai assertions in test_recorder

tests/test_recorder.js
=> refactor: Rewrite mikealRequest recorder tests using got

package-lock.json, package.json, tests/test_intercept.js, tests/test_request_overrider.js
This test came in on 3e2372689533e6c54e0a16717488459264c20755 to fix #120.  I've replaced it with a test that tests the behavior that was fixed, instead.
Ref #1777
=> Rewrite hyperquest integration test

tests/test_recorder.js
There's a lot more cleanup that could happen here, though I wanted to keep the first pass modest since it's a big file.
I added a top-level `let` to take care of the server cleanup in one place.
=> refactor: Mocha DSL for recorder tests, first pass

.travis.yml
Whichever of this or #1787 that lands first, the other will need updating.
=> ci: Lint only once

tests/test_intercept.js, tests/test_reply_function_sync.js
- Rewrite some mikealRequest tests using got
- Use some chai where things are changing anyway
- Some stylistic cleanup
- Break out one set of assertions into its own test
- Add some TODO comments
=> refactor: Some cleanup in test_intercept

lib/back.js, lib/common.js, lib/intercepted_request_router.js, lib/interceptor.js, lib/match_body.js, lib/playback_interceptor.js, lib/recorder.js
Fixes https://github.com/nock/nock/pull/1754#issuecomment-571531407
=> fix: use typeof instead of instanceof

tests/test_define.js
This is set in `got_client.js`.
=> Remove a spurious `{ retry: 0 }`

package-lock.json, package.json, tests/test_fake_timer.js, tests/test_reply_headers.js
=> Bump lolex and sinon

.github/workflows/release.yml, .travis.yml
addresses https://github.com/nock/nock/issues/1871
=> move semantic-release to GitHub Action

tests/test_allow_unmocked.js, tests/test_allow_unmocked_https.js
Merging the commit from #1894 into `beta`.
=> refactor(test): use Mocha DSL for allow unmocked (#1894)

.github/workflows/continuous-integration.yaml, .github/workflows/release.yml, .travis.yml, README.md, index.js, lib/back.js, lib/common.js, lib/intercept.js, package-lock.json, package.json, tests/test_allow_unmocked.js, tests/test_allow_unmocked_https.js, tests/test_basic_auth.js, tests/test_body_match.js, tests/test_define.js, tests/test_intercept.js, tests/test_net_connect.js, tests/test_query.js, tests/test_recorder.js, tests/test_reply_function_async.js, tests/test_reply_function_sync.js, tests/test_scope.js, types/index.d.ts, types/tests.ts
=> Release beta branch as 12.x

.github/workflows/continuous-integration.yaml
addresses https://github.com/nock/nock/issues/1883#issuecomment-586746643
=> ci(fix-formatting): avoid error if there are no changes to commit

.github/workflows/continuous-integration.yaml, README.md, index.js, lib/back.js, lib/common.js, lib/intercept.js, package-lock.json, package.json, tests/test_allow_unmocked.js, tests/test_allow_unmocked_https.js, tests/test_basic_auth.js, tests/test_body_match.js, tests/test_define.js, tests/test_intercept.js, tests/test_net_connect.js, tests/test_query.js, tests/test_recorder.js, tests/test_reply_function_async.js, tests/test_reply_function_sync.js, tests/test_scope.js, types/index.d.ts, types/tests.ts
I have reworded the commit messages which had the `BREAKING CHANGE` in the body to now include the `:`
Merging this PR into master will trigger the 12.0.0 release we want
=> node v12 (fixed commit messages)

tests/test_common.js
All in the name of prepping for Mocha DSL.
=> refactor(test): Chai assert common utilities

tests/test_intercept.js
Ref #1305
Most of the tap assertions left here are in tests which should be rewritten or removed.
=> refactor(test_intercept): Chai assertions for most of the tests

tests/test_abort.js, tests/test_common.js, tests/test_recorder.js, tests/test_reply_with_file.js, tests/test_scope.js
I had to reopen https://github.com/nock/nock/pull/1919
=> refactor(test): Mocha DSL for common utilities

tests/test_header_matching.js
The tests themselves were not modified, but they were reorganized so the git diff is a mess.
=> refactor(test): Mocha DSL for header matching

CONTRIBUTORS.md, README.md
=> replace greenkeeper with dependabot

CONTRIBUTORS.md, README.md, package-lock.json, package.json
There were some conflicts between master and beta. So when I cut next off of master to merge beta in, resolutions were needed. This brings the new next branch into beta. 
The only conflicts were with formatting in the README, but since I can't push to upstream, it has to be resolved via a PR.
=> Merge next into beta

CHANGELOG.md, lib/intercepted_request_router.js, rfcs/rfc-001.md
=> build: remove more "master"

.github/workflows/continuous-integration.yaml
See https://nodejs.org/en/about/releases/
=> ci(test): stop testing in Node 13

.github/dependabot.yml
[Dependabot docs](https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates).
Closes #1958.
=> chore: Add Dependabot config

tests/test_recorder.js
`recorder.js` has a block of code that skips storing the output of
requests initiated during another recording session.
The coverage for this block was not being covered when the tests where
run via Mocha and only covered via Tap by coincidence.
`'http request without callback should not crash'` was the culprit of the
coincidence via Tap as it never properly waited for the request to end
before cleaning up. Therefore subsequent tests would start a new
recording session and enter the block of code in question.
That test was updated to wait until the response has ended before
calling `done` on the test.
Then a new test was added to explicitly test the logic of skipping
recording of requests from previous sessions.
This issue was discovered while debugging …
=> test(recorder): skip requests from previous sessions

README.md
Just a quick fix to the README now that the latest version is 13!
=> docs: Update "12.x" to "Nock 12 and later"

lib/socket.js, tests/test_socket.js
https://nodejs.org/docs/latest/api/tls.html#tls_tlssocket_encrypted
https://github.com/nodejs/node/blob/295e766c2782d6d83e33004f7c2204c0a8d52655/lib/_tls_wrap.js#L507-L509
Fixes: https://github.com/nock/nock/issues/2147
=> fix(socket): add encrypted attribute for secure requests

lib/common.js
=> refactor: Fix typo in common.js

lib/intercepted_request_router.js, tests/test_request_overrider.js
=> fix: looking up timeout on agent with no options

lib/common.js, lib/match_body.js, package-lock.json, package.json, tests/test_common.js
Closes #2530 
This PR removes lodash with equivalent functionality.
=> remove lodash

.github/workflows/continuous-integration.yaml, package-lock.json, package.json
=> Revert "chore(deps-dev): bump @definitelytyped/dtslint from 0.0.163 to 0.0.183"

lib/intercept.js
=> fix: add fetch to the restore function

.all-contributorsrc, .github/workflows/continuous-integration.yaml, README.md
this should trigger CI against the `beta` branch @mikicho
OOps sorry for the unrelated changes, I created the PR against main at first
=> ci: run an all release branches

lib/create_response.js, tests/test_fetch.js
=> fix: avoid closing an already closed stream

package-lock.json, package.json, tests/got/test_intercept.js
=> fix: support lowercase HTTP request methods

lib/intercept.js, tests/test_fetch.js
This is probably a redundant code from my early work on this PR.
=> stop forward request headers

package-lock.json, package.json
* Increase `ClientRequest` compatibility.
* Publish a new version to release #2769
=> fix: upgrade interceptors (+trigger release)

package-lock.json, package.json, tests/test_fetch.js
=> fix(fetch): support fetch redirect

package-lock.json, package.json, tests/test_fetch.js
=> fix(fetch): rebase relative redirect URL against `request.url`

package-lock.json, package.json
closes https://github.com/nock/nock/issues/2794
=> fix(fetch): await response listener before resolving the response promise

lib/create_response.js, lib/intercept.js, tests/test_fetch.js
=> fix(fetch): add support for aborting requests using AbortSignal

lib/recorder.js, tests/test_fetch.js
=> recompress fetch body on record

package.json
=> fix(node-version): update node minimum version

package-lock.json, package.json, tests/test_fetch.js
=> fix request body unusable in update mode

package-lock.json, package.json, tests/test_fetch.js
=> fix(fetch): cloned response return correct url

lib/intercept.js, package-lock.json, package.json, tests/got/test_intercept.js
=> fix(ClientRequest): support get with body

README.md, lib/common.js, lib/handle-request.js, lib/intercept.js, lib/interceptors/builtin.js, lib/interceptors/undici.js, package-lock.json, package.json, tests/test_undici.js
Based on the work I did in the "cleanp" branch (v15).
Basic undici support based on undici's MockAgent approach.
The test coverage is super basic, because I'm wondering how to avoid duplicate tests (bultin modules, fetch, undici, etc)
#2183
=>  feat(undici): basic support

package-lock.json, package.json, tests/got/test_intercept.js, tests/test_unix_socket.js
closes #2839
And support more than 30 headers
=> fix: upgrade interceptors
